README.md
workspaces-workflow.md

Also move previous README to a separate document regarding remote terraform states and workspaces workflow.

Fix main README

---

.gitignore
aws/terraform/README.md
azure/terraform/README.md

Add how-to generate SSH keys to documentation

Add how-to generate SSH keys to documentation

---

gcp/terraform/terraform.tfvars

Remove specific OS Image Version from variables file

Remove specific OS Image Version from variables file

---

gcp/terraform/create_remote_state/bucket.tf
gcp/terraform/remote-state.tf
gcp/terraform/terraform.tfvars
gcp/terraform/variables.tf

Remove references to CSS assets in GCP configuration

Remove references to CSS assets in GCP configuration

---

gcp/terraform/variables.tf

- Declare sap_vip.
- Format `variables.tf` with `terraform fmt`

Declare sap_vip & terraform fmt

---

aws/terraform/instances.tf
aws/terraform/network.tf
aws/terraform/variables.tf
azure/terraform/image.tf
azure/terraform/keys.tf
azure/terraform/network.tf
azure/terraform/terraform.tfvars
azure/terraform/variables.tf

Run `terraform fmt` in all `*.tf` files before configuring CI checks for the repo.

terraform fmt

---

gcp/terraform/.travis.yml

Add Travis CI support for validating Terraform configuration

Add Travis CI support for validating Terraform configuration

---

.travis.yml

Fix Travis yml

---

.travis.yml
README.md
azure/terraform/resources.tf

* Add verbose output to travis script to see when build fails where the problem is located.
* Add travil build status to README.md

Further travis configuration and tests

---

.travis.yml

Check JSON files in Travis

---

.travis.yml
aws/terraform/instances.tf
aws/terraform/keys.tf
aws/terraform/network.tf
azure/terraform/README.md
azure/terraform/image.tf
azure/terraform/init-iscsi.sh
azure/terraform/init-nodes.sh
azure/terraform/network.tf
azure/terraform/outputs.tf
azure/terraform/resources.tf
azure/terraform/virtualmachines.tf
azure/terraform/virtualmachines.tf-publicimg
gcp/terraform/startup.sh
workspaces-workflow.md

1. Fix bug in shell script
2. Add shell script testing to Travis
3. Add support for workspaces to AWS configuration
4. Add support for workspaces to Azure configuration

Fixes & Terraform workspaces support

---

libvirt/terraform/README.md

update link to hana.sls and cluster.sls in readme

README update to fix link to pillar files

---

gcp/terraform/startup.sh

This PR fixes a bug that currently prevents deployment due to changes in upstream scripts from Google.

gpc: Fix deployment bug and merge upstream changes in startup.sh

---

libvirt/terraform/README.md
libvirt/terraform/main.tf
libvirt/terraform/variables.tf

- Some typos fixes
- Add a default value for `additional_repos`

Minor fixes

---

gcp/terraform/startup.sh

This PR:
- Fixes a bug regarding versioning of the module-public-cloud on 12 vs 15.
- Aborts startup if no regcode is present and the user is trying to install HANA.

Fix module public cloud

---

gcp/terraform/README.md
gcp/terraform/disks.tf
gcp/terraform/init-iscsi.tpl
gcp/terraform/instances.tf
gcp/terraform/outputs.tf
gcp/terraform/startup.sh
gcp/terraform/templates.tf
gcp/terraform/terraform.tfvars
gcp/terraform/variables.tf

This PR adds support for SBD stonith using an iSCSI server running SLES 12 SP3/SP4.
Minor fixes included as well.

Add iSCSI server for SBD stonith

---

libvirt/terraform/terraform.tfvars.example

Add missing tfvars example file

Add terraform.tfvars.example for libvirt

---

salt/hana_node/hana_packages.sls

Adapt shaptools pkg installation after: https://github.com/SUSE/shaptools/pull/24

Adatp shaptools pkg installation name

---

.travis.yml
README.md
libvirt/terraform/README.md

This PR:
- Fixes the Terraform version in Travis
- Enables e-mail notification in Travis
- Updates the documentation specifying the Terraform version
- Updates the libvirt documentation adding links to the Libvirt provider packages & source

Fix Terraform version

---

aws/terraform_salt/salt_provisioner.tf
azure/terraform_salt/salt_provisioner.tf
gcp/terraform_salt/salt_provisioner.tf
libvirt/terraform/variables.tf
salt/hana_node/hana_packages.sls

Sorry guys, I have broken the project with the last PR merge (scenario_type added to iscsi machine in stead of hana machines)...
Here the fix for that.

Fix scenario type grains usage

---

README.md
libvirt/terraform/README.md

- we don't need the contributing statement, it is pretty obvious that you need to fork and send PR.
-  introduce quick-start. The fact of working-space is really crucial for the naming, is not something cosmetic.

remove obvious contributing and improve quickstart

---

salt/README.md
salt/default/setup.sls
salt/default/timezone.sls
salt/hana_node/cluster_packages.sls
salt/hana_node/hana_packages.sls
salt/hana_node/iscsi_initiator.sls
salt/hana_node/mount.sls
salt/hana_node/sap_inst.sls
salt/pre_installation/packages.sls

fix one part of: https://trello.com/c/rp9qZp6B/761-retry-package-installation-if-it-fails

Make pkg.install more resilient

---

libvirt/terraform/README.md

Add more structure, fix links.
It is a first step to have more essential documentation. ( I could modify more , but I think we can wait after this 2 prs are merged)

Simplify and remove superficial information

---

aws/terraform_salt/salt_provisioner.tf
azure/terraform_salt/salt_provisioner.tf
gcp/terraform_salt/salt_provisioner.tf
libvirt/terraform/modules/host/salt_provisioner.tf

Fix a regression that appears during the last GCE refactoring...
EDIT: fixed for all provider

Fix VM name on all Cloud providers

---

salt/monitoring/init.sls
salt/monitoring/prometheus/prometheus.yml
salt/monitoring/prometheus/rules.yml
salt/pre_installation/minion_configuration.sls

this PR provide  a minmal skaffold for prometheus alerts

add minimal structure for alerts 

---

salt/hana_node/init.sls

Handle default for grain monitoring

---

libvirt/terraform/modules/hana_node/main.tf
libvirt/terraform/modules/hana_node/variables.tf
libvirt/terraform/modules/host/main.tf
libvirt/terraform/modules/host/variables.tf
libvirt/terraform/modules/iscsi_server/main.tf
libvirt/terraform/modules/iscsi_server/variables.tf
libvirt/terraform/modules/monitoring/main.tf
libvirt/terraform/modules/monitoring/variables.tf

fix #113 . Discussed above. the running variable is not needed for our usa-case so a variable less is less behaviour to maintain

remove Running variable

---

pillar_examples/automatic/cluster.sls
pillar_examples/automatic/hana.sls

I forgot to update the pillar examples in https://github.com/SUSE/ha-sap-terraform-deployments/pull/120

Fix qa_mode in pillar examples

---

aws/README.md
azure/README.md
gcp/README.md

explain the difference between dirs which isn't implicit for newcomers

Add readme to explain difference between dirs

---

aws/terraform_salt/README.md

https://github.com/MalloZup/ha-sap-terraform-deployments/tree/improve-aws-doc/aws/terraform_salt
this PR doesn't do much. But it provide more a friendly structure for users and structure the information better then before.

[AWS]: Restructure, minimalize doc

---

gcp/terraform_salt/README.md

make more clear for newcomers how to create the keys

update doc for gcp

---

README.md
libvirt/README.md

move the libvirt doc to libvirt. 
Make the initial doc a index only
https://github.com/MalloZup/ha-sap-terraform-deployments/tree/doc-readme

minimalize initial doc and move it to libvirt

---

aws/salt_provisioner.tf
azure/README.md
azure/image.tf
azure/instances.tf
azure/monitoring.tf
azure/network.tf
azure/outputs.tf
azure/salt_provisioner.tf
azure/terraform.tfvars.example
gcp/salt_provisioner.tf
libvirt/modules/monitoring/salt_provisioner.tf
salt/hana_node/cluster_packages.sls
salt/monitoring/prometheus/prometheus.yml
salt/pre_installation/ha_repos.sls

azure monitoring (non module)

---

libvirt/terraform.tfvars.example
libvirt/variables.tf
pillar_examples/automatic/cluster.sls
pillar_examples/automatic/hana.sls
pillar_examples/aws/cluster.sls
pillar_examples/azure/cluster.sls
pillar_examples/libvirt/cost_optimized/cluster.sls
pillar_examples/libvirt/performance_optimized/cluster.sls

For automatic pillar enable if monitoring_enabled
I'm testing this now
(@stefanotorresi  added in CC just as a turist for moment but feel free to look even :) )
fix #181

Adapt pillars to disable ha_exporter by default

---

pillar_examples/automatic/hana.sls

FIX: add endif missing

---

salt/monitoring/prometheus/rules.yml

- change name of alert
( before it was duplicate with 1 )

change name of alert

---

salt/monitoring/prometheus/rules.yml
salt/monitoring/provisioning/dashboards/grafana-sap-hana-dashboard.json

- adjust alert
- add 2 red/green visualisation

Adjust alert and improve dashboard

---

libvirt/main.tf
libvirt/modules/monitoring/main.tf
libvirt/modules/monitoring/salt_provisioner.tf

fix issue #193
I will test this pr

Hardcode monitoring host to 1

---

pillar_examples/automatic/cluster.sls
pillar_examples/aws/cluster.sls
pillar_examples/azure/cluster.sls

https://github.com/SUSE/ha-sap-terraform-deployments/issues/208

Enable ntp/chrony in cloud provider in the pillar

---

salt/hana_node/iscsi_initiator.sls

lower the iscsi discovery timeout

---

salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
salt/monitoring/provisioning/dashboards/ha-sap-hana-detailed-timestamp.json

- add timestamp ring errors
-   add corosync metrics (votes, quorate and ring errors)

Update dashboards with new corosync metrics

---

aws/instances.tf

Fix instance type for monitoring node (aws)

---

salt/salt_provisioner_script.tpl

Fix #221
Tested in AWS both with and without qa_mode.

Disable colors if qa_mode = true

---

salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json

The Health of device is the last one at the buttom right `SBD`
A potential user will need to change the device/s names and add others. 
___
you can see it here: 
http://10.162.32.94/d/Q5YJpwtZk1/ha-sap-hana-cluster-status?orgId=1

add sbd device visualisation

---

salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
salt/monitoring/provisioning/dashboards/ha-sap-hana-detailed-timestamp.json

remove hard coded values from provisioned grafana dashboards

---

salt/monitoring/prometheus/rules.yml
salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
salt/monitoring/provisioning/dashboards/ha-sap-hana-detailed-timestamp.json

updates metrics naming according to ClusterLabs/ha_cluster_exporter#48

Refactor metric names

---

salt/salt_provisioner_script.tpl

Now that we have salt-minion included in public cloud images, registration is not needed anymore for HANA/cluster nodes. And we have to make sure to not install packages outside of images.
This change does not concern iscsi/monitoring servers.
Tests:
- AWS with and without QA_MODE: OK
- GCP with and without QA_MODE: OK
- Azure with and without QA_MODE: OK
I didn't test in libvirt but I think it is not impacted by this change, @arbulu89 @MalloZup WDYT?

Disable registration in QA_MODE

---

salt/monitoring/prometheus/rules.yml

add generic alert for sbd devices

Add generic SBD alerts for unhealthy devices

---

salt/monitoring/prometheus/rules.yml
salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json

according to ClusterLabs/ha_cluster_exporter#66

update metrics names

---

salt/monitoring/prometheus/rules.yml
salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json

I forgot to rename these attributes in #236

Fix some metric attributes changes

---

README.md
aws/README.md
aws/terraform.tfvars.example
azure/README.md
azure/terraform.tfvars.example
doc/qa.md
gcp/README.md
gcp/terraform.tfvars.example
libvirt/README.md
pillar_examples/README.md

This PR improves documentation about QA and public cloud:
- Add a global QA documentation
- Public cloud doc standardization 
- Add more details about how to use pillars and centralize documentation to avoid duplication and easier maintenance.

Improve documentation

---

salt/monitoring/prometheus/rules.yml
salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
salt/monitoring/provisioning/dashboards/ha-sap-hana-detailed-timestamp.json

this PR includes the various changes demonstrated in the 04 Nov 2019 sprint review, plus the "Last CIB change" panel, as shown below:
you can play with this new dashboard at http://10.162.32.207/d/Q5YJpwtZk1/ha-cluster-status

Grafana dashboard improvements

---

salt/monitoring/provisioning/dashboards/ha-sap-hana-detailed-timestamp.json

Update HANA monitoring dashboard to select the monitoring database.
Now, all the available databases in the metrics are available.
PD: I have not found any option to set the filter for the panels in a variable, to make it easier to change without changing all the panels...

Add multi tenant HANA monitoring dashboard

---

azure/image.tf
azure/instances.tf
azure/terraform.tfvars.example
salt/hana_node/network.sls
salt/install-salt-minion.sh
salt/iscsi_srv/init.sls
salt/iscsi_srv/registration.sls
salt/monitoring/init.sls
salt/salt_provisioner_script.tpl

This PR aims to fix:
1. Issue with monitoring server deployment in Azure. Provide customizable image
2. Fix deployment when registration code is not provided. Important things:
- Registration of iscsi server is managed now in salt
- Registration is done only if code is provided. Otherwise salt installation will be tried from current repositories.
Pending to be tested properly!

Fix the deployment when execution is done without reg code

---

libvirt/modules/drbd_node/salt_provisioner.tf

super-small change I forgot to mention in #239

make drbd count setting consistent with latest changes in #254

---

salt/monitoring/prometheus/rules.yml

this PR add 3 new alerts for the DRBD resources

Add drbd allerts for the 3 new metrics

---

salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json

ADDED:
I have added the position at the bottom (we can still change it later on)
@stefanotorresi  I think we can still merge this and modify it later accordingly to your modification.
We have already the alerts in place so a table is perfect. 
I'm ok if you want to change the display/position later on your pr :+1:

Add drbd table about resources

---

.gitignore
libvirt/main.tf
libvirt/modules/drbd_node/salt_provisioner.tf
pillar_examples/automatic/drbd/drbd.sls
salt/drbd_node/files/templates/drbd_cluster.j2
salt/drbd_node/parted.sls
salt/netweaver_node/init.sls
salt/netweaver_node/nfs.sls

I have updated some drbd options to accomodate the created NFS on top of DRBD for NW specifically.
@nick-wang Could you have a look?

Accomodate the drbd deployment for NW specific

---

doc/monitoring.md
salt/drbd_node/files/notify-split-brain-haclusterexporter-suse-metric.sh

Update monitoring docs

---

salt/monitoring/provisioning/dashboards/multi-cluster-overview.json

This is mostly what I've shown in my progress report during the latest sprint review.
I've included some new time charts and fixed a couple of broken queries.
Here is a screenshot:
Live demo is here: http://10.162.30.194/d/5b0v3y-Wz1/multi-cluster-overview
It's not 100% incomplete, but I'd rather merge this first version before continuing the work.

Initial implementation of Multi-Cluster Grafana dashboard

---

README.md
aws/terraform.tfvars.example
aws/variables.tf
azure/terraform.tfvars.example
azure/variables.tf
gcp/terraform.tfvars.example
gcp/variables.tf
salt/monitoring/prometheus/prometheus.yml

We need to backport #303 from master to develop.

Sync PR #303 from master to develop branch

---

salt/cluster_node/ssh.sls
salt/drbd_node/files/templates/drbd_cluster.j2

Fix the error message of drbd_json_template and habootstrap(crmsh)

Minor fixup

---

README.md

Third time's the charm (hopefully).

[develop] Fix a typo and some grammar improvements

---

aws/network.tf
azure/network.tf
doc/monitoring.md
gcp/network.tf
salt/monitoring/prometheus/prometheus.yml

see https://github.com/ClusterLabs/ha_cluster_exporter/pull/122

Change port 9002 to 9964 hacluster exporter

---

aws/network.tf
azure/network.tf
doc/monitoring.md
gcp/network.tf
salt/monitoring/prometheus/prometheus.yml

Change haexporter port develop

---

aws/network.tf
azure/network.tf
doc/monitoring.md
gcp/network.tf
salt/monitoring/prometheus/prometheus.yml

please merge and backport to develop 
thx!

change ha_cluster_exporter port to 9664

---

aws/network.tf
azure/network.tf
doc/monitoring.md
gcp/network.tf
salt/monitoring/prometheus/prometheus.yml

backport of hotfix #347 to develop

Backport ha exporter target port change

---

aws/network.tf
azure/network.tf
doc/monitoring.md
gcp/network.tf
pillar_examples/automatic/hana/hana.sls
salt/monitoring/prometheus/prometheus.yml

see https://github.com/SUSE/hanadb_exporter/pull/55 
https://github.com/SUSE/hanadb_exporter/pull/56/files

change hanadb_exporter port to 9668

---

aws/network.tf
azure/network.tf
doc/monitoring.md
gcp/network.tf
pillar_examples/automatic/hana/hana.sls
salt/monitoring/prometheus/prometheus.yml

Backport hana exporter target port change

---

salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
salt/monitoring/provisioning/dashboards/multi-cluster-overview.json

compat fixes for ClusterLabs/ha_cluster_exporter#123

Hotfix grafana dashboards

---

README.md
salt/deployment.sh
salt/hana_node/hana_inst_media.sls

This PR fix only 2 small issue for idempotency we had.

[idempotency]: salt-states deployment.sh script

---

salt/monitoring/prometheus/prometheus.yml
salt/monitoring/provisioning/dashboards/netweaver-cluster-status.json
salt/netweaver_node/files/pillar/netweaver.sls

This pr doesn't do much.
It add the `sap_host_exporter` port to prometheus and a dummi dashboard for grafana, which I want to improve tomorrow with some real data/graphs.
perhaps take a look if you like the name of the dashboard. I think should be ok

Firs enablement for sap_host_exporter

---

salt/netweaver_node/files/pillar/netweaver.sls

this PR build on https://github.com/SUSE/sapnwbootstrap-formula/pull/33
adding @stefanotorresi  as non-official reviewer so he can see what we need to enable the exporter in salt

Enable sap host exporter

---

salt/netweaver_node/files/pillar/netweaver.sls

Fix logic for activating exporter

---

libvirt/modules/hana_node/salt_provisioner.tf
pillar_examples/automatic/hana/cluster.sls

I forgot to add the `hana_cluster_vip` entry to the grains file and update the pillar file accordingly.

Add hana_cluster_vip to grains

---

gcp/modules/hana_node/salt_provisioner.tf

Remove the `+` character that was badly added...

Remove bad character added by PR#440

---

salt/netweaver_node/nfs.sls

During the nfs share initilization creating folders, there is a race conditions that if 2 nodes connect in the same moment, the folder are not created, making the netweaver installation fail.
This PR changes how the folders are created, just creating with the 1st node. 
Besides that, I have changed the way nfs server availability is checked using showmount (and nc in aws case, as efs storage doesn't provide output for showmount)

Fix race condition in nfs share connection

---

salt/cluster_node/ha/iscsi_initiator.sls

Patch to fix the last https://github.com/SUSE/ha-sap-terraform-deployments/pull/504 changes.
In some sporadic cases (specially in the cloud instances) the output of `lsscsi -i` doesn't return the disk id until some seconds are passed. This was generating an output like this: 
```
[2:0:0:0]    disk    ATA      SK hynix SC311 S 0P10  /dev/sda   -
```
And the next device creation: `/dev/disk/by-id/scsi--`
To fix this, I have included an active checking system to wait until the disk id is available in the command output to proceed with the correct data

Fix lsscsi command usage to manage `-` output

---

generic_modules/common_variables/outputs.tf
generic_modules/common_variables/variables.tf

I forgot to commit the `common_variables` module

Commit missing common_variables module

---

salt/provision.sh

In azure deployment with sle15sp2 image we have failure otherwise

Handle case where srv/salt already exists

---

azure/README.md

add minimal doc for documenting bastion feature

Add documentation for bastion

---

pillar_examples/automatic/drbd/drbd.sls
salt/drbd_node/custom_handlers.sls

Fix drbd pillar file to use the splitbrain handler properly

Correct drbd pillar file to use the splitbrain handler correctly

---

README.md
aws/terraform.tfvars.example
azure/terraform.tfvars.example
doc/sap_software.md
gcp/terraform.tfvars.example
libvirt/terraform.tfvars.example

New documentation about how to setup the SAP software required for the installation.
Please, have a deep look, and try to understand how we configure our files, to see if there is something wrong or missing.
If we don't check if what says is good, it's just more bunch of text that might not help.
Do the exercise with our buckets to understand how they are structured.

Add new documentation about SAP sofware usage

---

aws/modules/netweaver_node/variables.tf
aws/terraform.tfvars.example
aws/variables.tf
azure/modules/netweaver_node/variables.tf
azure/terraform.tfvars.example
azure/variables.tf
gcp/modules/netweaver_node/variables.tf
gcp/terraform.tfvars.example
gcp/variables.tf
libvirt/modules/netweaver_node/variables.tf
libvirt/terraform.tfvars.example
libvirt/variables.tf

Changing the default netweaver archives extraction directory.
Related to https://github.com/SUSE/sapnwbootstrap-formula/pull/66

Update the default netweaver extraction location

---

aws/README.md
azure/README.md
gcp/README.md

Updating the documentation with correct commands:
- commands to generate keys
- command to list gcp images

Update readme ssh commands to generate keys and command to list GCP gcloud images

---

blue_horizon/azure/data/azure-types.json
blue_horizon/azure/sources/variables.tf.json

Initial `Size cluster` page configuration page. It will need some work though

Add cluster sizing page data file

---

blue_horizon/azure/sources/main.tf
blue_horizon/azure/sources/variables.tf.json

Simplify variables.
How it looks with this PR

WIP: Set to default some variables and remove user input

---

blue_horizon/azure/customization.json
blue_horizon/azure/locales/custom-en.yml
blue_horizon/azure/sources/main.tf
blue_horizon/azure/sources/outputs.tf
blue_horizon/azure/sources/variables.tf.json

Some changes to make Blue-horizon work properly with the current `develop` branch.
After this, I won't do more changes. 
@petersatsuse will take care of tuning the variables, the text and the size cluster panel

Improve blue-horizon variables usage

---

blue_horizon/azure/data/azure-types.json
blue_horizon/azure/locales/custom-en.yml
blue_horizon/azure/locales/en.yml
blue_horizon/azure/sources/main.tf
blue_horizon/azure/sources/variables.tf.json

Text changes to provide more context
adaption of the instance size to new types
fix large instance size as it had complete wrong settings

Sap blue horizon text changes

---

.shellcheckrc
.travis.yml
salt/provision.sh

https://github.com/koalaman/shellcheck is awesome, but wtf, we're still using shell. :rofl:

add shellcheck to CI and apply fixes to provision.sh

---

salt/provision.sh

Fix some issues introduced in: https://github.com/SUSE/ha-sap-terraform-deployments/pull/588
With these changes the functionality is reverted following the bash best practices applied before.
- Remove `-x` option from `set` to avoid debugging more. Some info at: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
- Add `-e` to colored messages to escape the characters. https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
- Remove quoted parameters from some points (VERSION_ID and `set_colored_output`) to have the correct behaviour. These quotes were introducing incorrect usage of variables
- Fix message in QA mode salt execution

Fix some provision.sh bash malfunctions

---

azure/infrastructure.tf
azure/variables.tf

Use Azure service principal. More info in: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret

Use azure service principal variables to authenticate

---

salt/hana_node/mount/azure.sls

Port to `sap-blue-horizon` branch of: https://github.com/SUSE/ha-sap-terraform-deployments/pull/620
FYI: @petersatsuse

Fix how the lvm is created in azure with multiple luns

---

salt/cluster_node/aws_data_provider.sls

Fix AWS data provider installation as the process has been changed. Here the followed steps:
https://docs.aws.amazon.com/sap/latest/general/data-provider-install.html

Fix aws data provider installation

---

salt/cluster_node/ha/network.sls
salt/cluster_node/monitoring.sls
salt/monitoring_srv/grafana.sls
salt/monitoring_srv/loki.sls

Backport PR#600 to `master` branch for 15-SP3.
Tested manually on my lab.

Backport network restart and remove unneeded restart

---

salt/cluster_node/aws_data_provider.sls

Sync develop from master after fixing: #627 and #629

Sync Develop

---

salt/netweaver_node/nfs.sls

Fix for: https://github.com/SUSE/ha-sap-terraform-deployments/issues/633
The error happens in the `nfs.sls` file. Time to time (rarely in fact), the mount/create folders/unmount process doesn't create the folder permanently. I cannot really say what happens.
The truth is that in failed deployments, the created folder are not there, even when the salt states passed. 
One of my assumptions is that the next removal takes place, as the unmount is not instant, but I cannot assure this.
That's why I have added some different delays. With this change I have not reproduced the error in 10 tries.
FYI: @ab-mohamed

Fix nfs connection error during nw installation

---

salt/macros/download_from_google_storage.sls

Use correct python version for gcloud and gsutil utilities
Fix for: https://github.com/SUSE/ha-sap-terraform-deployments/issues/669

Correct python version for gcloud and gsutil utilities

---

aws/terraform.tfvars.example
azure/terraform.tfvars.example
gcp/terraform.tfvars.example
libvirt/terraform.tfvars.example

Fix and updated some tfvars template examples entries
Fix for: https://github.com/SUSE/ha-sap-terraform-deployments/issues/656
FYI @ab-mohamed

tfvars template examples notes

---

generic_modules/salt_provisioner/main.tf
powervs/infrastructure.tf
powervs/main.tf
powervs/modules/hana_node/main.tf
powervs/modules/hana_node/output.tf
powervs/modules/hana_node/salt_provisioner.tf
powervs/modules/hana_node/variables.tf
powervs/outputs.tf
powervs/terraform.tfvars.example
powervs/variables.tf
salt/hana_node/hana_inst_media.sls
salt/hana_node/mount/init.sls
salt/hana_node/mount/powervs.sls
salt/os_setup/init.sls
salt/os_setup/registration.sls
salt/provision.sh

The goal of this is to deploy a single HANA on PowerVS instance (no HANA system replication or HA).

Initial commit for powervs

---

openstack/main.tf
openstack/terraform.tfvars.example
openstack/variables.tf

Correct some variables values for openstack to pass the variables validation

openstack - correct variables validation

---

generic_modules/common_variables/hana_variables.tf
generic_modules/common_variables/variables.tf
powervs/infrastructure.tf
powervs/main.tf
powervs/modules/hana_node/main.tf
powervs/modules/hana_node/salt_provisioner.tf
powervs/modules/hana_node/variables.tf
powervs/modules/shared_disk/main.tf
powervs/modules/shared_disk/output.tf
powervs/modules/shared_disk/variables.tf
powervs/variables.tf

This PR enables the deployment of multiple IBM PowerVS instances where HANA will be installed.  A shared SCSI LUN is also created so that HANA System Replication and SLE HA can be setup with with the SAPHanaSR resource agent.

Deploy shared storage, HANA HSR, SLE HA

---

libvirt/main.tf
libvirt/terraform.tfvars.example
libvirt/variables.tf

Make hardcoded bridge device br0 configurable by a variable

Make bridge device br0 configurable

---

openstack/terraform.tfvars.example
openstack/variables.tf
salt/bastion/init.sls
salt/bastion/sapinst.sls

Deployment failed on using rootdisk as data source.

add support for rootdisk as data_disk_type and change default drbd fencing to sbd

---

libvirt/README.md

Extending documentation for libvirt with xsltproc as requirement.

Add xsltproc to libvirt requirements

---

aws/modules/drbd_node/main.tf
aws/modules/drbd_node/salt_provisioner.tf
aws/modules/hana_node/main.tf
aws/modules/hana_node/salt_provisioner.tf
aws/modules/netweaver_node/main.tf
aws/modules/netweaver_node/salt_provisioner.tf
azure/modules/drbd_node/main.tf
azure/modules/drbd_node/salt_provisioner.tf
azure/modules/hana_node/main.tf
azure/modules/hana_node/salt_provisioner.tf
azure/modules/iscsi_server/main.tf
azure/modules/netweaver_node/main.tf
azure/modules/netweaver_node/salt_provisioner.tf
gcp/modules/drbd_node/main.tf
gcp/modules/drbd_node/salt_provisioner.tf
gcp/modules/hana_node/main.tf
gcp/modules/hana_node/salt_provisioner.tf
gcp/modules/netweaver_node/main.tf
gcp/modules/netweaver_node/salt_provisioner.tf
libvirt/modules/drbd_node/salt_provisioner.tf
libvirt/modules/hana_node/salt_provisioner.tf
libvirt/modules/netweaver_node/salt_provisioner.tf
openstack/modules/drbd_node/salt_provisioner.tf
openstack/modules/hana_node/salt_provisioner.tf
openstack/modules/netweaver_node/salt_provisioner.tf

Correct padding on integers that have a "leading 0".

correct padding on integers<10

---

salt/hana_node/mount/gcp.sls

This makes it possible to run the HANA LVM states more than once on GCP.

make HANA LVM setup idempotent on GCP

---

openstack/cloud-config.tpl
openstack/infrastructure.tf
openstack/main.tf
openstack/modules/bastion/main.tf
openstack/modules/bastion/variables.tf
openstack/modules/iscsi_server/main.tf
openstack/modules/iscsi_server/salt_provisioner.tf
openstack/variables.tf

- openstack: possibility to use existing volume on bastion NFS server
be45329
- openstack: fix cloud-init and provide template file
54d5891
- openstack: smaller fixes
29e4201
- openstack: fix iscsi provisioning

openstack: use existing volume on bastion NFS server and smaller fixes

---

powervs/infrastructure.tf
powervs/modules/bastion/main.tf
powervs/modules/bastion/versions.tf
powervs/modules/hana_node/main.tf
powervs/modules/hana_node/versions.tf
powervs/modules/shared_disk/main.tf
powervs/modules/shared_disk/versions.tf
powervs/versions.tf

This PR removes the error which was commented by @stefanotorresi  in #759.

powervs: fix ibm cloud provider

---

requirements.yml

fixes Wait for cluster startup after corosync restart
(bsc#1190940)

master: bump habootstrap-formula to 0.4.4

---

requirements.yml

- merge `master` into `develop`
- bump `requirements.yml`

prepare develop for 8.0.0 release

---

salt/cluster_node/aws_data_provider.sls

aws: fix data-provider installation

---

aws/modules/drbd_node/main.tf
aws/modules/drbd_node/salt_provisioner.tf
aws/modules/hana_node/main.tf
aws/modules/hana_node/salt_provisioner.tf
aws/modules/iscsi_server/main.tf
aws/modules/iscsi_server/salt_provisioner.tf
aws/modules/monitoring/main.tf
aws/modules/netweaver_node/main.tf
aws/modules/netweaver_node/salt_provisioner.tf
aws/terraform.tfvars.example
aws/variables.tf
pillar/iscsi_srv.sls
pillar_examples/automatic/drbd/drbd.sls
salt/cluster_node/aws_data_provider.sls
salt/hana_node/mount/mount.sls
salt/netweaver_node/installation_files.sls

prepare develop for 8.0.0 release 

---

libvirt/cloud-config.tpl
libvirt/main.tf
libvirt/modules/drbd_node/main.tf
libvirt/modules/drbd_node/salt_provisioner.tf
libvirt/modules/drbd_node/variables.tf
libvirt/modules/hana_node/main.tf
libvirt/modules/hana_node/salt_provisioner.tf
libvirt/modules/hana_node/variables.tf
libvirt/modules/iscsi_server/main.tf
libvirt/modules/iscsi_server/salt_provisioner.tf
libvirt/modules/iscsi_server/variables.tf
libvirt/modules/monitoring/main.tf
libvirt/modules/monitoring/salt_provisioner.tf
libvirt/modules/monitoring/variables.tf
libvirt/modules/netweaver_node/main.tf
libvirt/modules/netweaver_node/salt_provisioner.tf
libvirt/modules/netweaver_node/variables.tf

This runs cloud-init if the package is installed.

libvirt: optional cloudinit

---

requirements.yml

* https://github.com/SUSE/salt-shaptools/pull/91

bump requirements to mitigate SLES 15 SP4 issues

---

salt/macros/download_from_google_storage.sls

Make `gcloud` and `gsutil` available for all users.

gcp: install google-cloud-sdk to /opt/google-cloud-sdk

---

libvirt/main.tf
libvirt/modules/hana_node/variables.tf
libvirt/modules/iscsi_server/salt_provisioner.tf
libvirt/modules/iscsi_server/variables.tf
libvirt/terraform.tfvars.example
openstack/modules/hana_node/main.tf

Some small fixes introduced due to latest LVM code changes and for the rarely used libvirt iscsi+sbd feature.

libvirt and openstack fixes

---

pillar_examples/automatic/hana/cluster.sls
pillar_examples/automatic/netweaver/cluster.sls

Updated token timeouts for AWS to reflect current best practice.

Timeout Updates (AWS)

---

README.md
aws/terraform.tfvars.example
azure/modules/majority_maker_node/main.tf
azure/modules/majority_maker_node/salt_provisioner.tf
azure/terraform.tfvars.example
gcp/terraform.tfvars.example
libvirt/terraform.tfvars.example
openstack/terraform.tfvars.example

Some smaller changes:
- [doc: update to SLES4SAP 15 SP4](https://github.com/SUSE/ha-sap-terraform-deployments/commit/b346305dd3832c6bb13256abd3e7341261893c5c)
- [doc: mention HANA 2.0 SPS 06 changes in terraform.tfvars](https://github.com/SUSE/ha-sap-terraform-deployments/commit/c9734cfaaf6a9d4153936db3eaeb51d2d2c61c04)
- [azure: fix custom majority maker node hostnames](https://github.com/SUSE/ha-sap-terraform-deployments/commit/764feee89726a4a614a1dd88b091ac09431ce104)

update doc to 15.4 / doc changes for HANA 2.0 SPS06 / majority maker hostname fix

---

requirements.yml

This fixes #887 and 
includes fixes and features from:
https://github.com/SUSE/saphanabootstrap-formula/pull/144
https://github.com/SUSE/saphanabootstrap-formula/pull/145
https://github.com/SUSE/saphanabootstrap-formula/pull/146
https://github.com/SUSE/saphanabootstrap-formula/pull/147
https://github.com/SUSE/saphanabootstrap-formula/pull/148
https://github.com/SUSE/habootstrap-formula/pull/90
https://github.com/SUSE/habootstrap-formula/pull/91
https://github.com/SUSE/sapnwbootstrap-formula/pull/96

bump requirements to fix #887 and other smaller things

---

salt/bastion/nginx.sls
salt/hana_node/mount/lvm.sls

* make sure nginx package is available for monitoring setup on SLES12 by providing it from packagehub
* [monitoring: fix nginx deployment on SLES12](https://github.com/SUSE/ha-sap-terraform-deployments/commit/412802448209d8752fe3eea650a646da11bb53a6)
* [simplify HANA lvm code to work on SLES12](https://github.com/SUSE/ha-sap-terraform-deployments/commit/c2eeace7a266936dfecb38f6d99df30a68c9b259)

fix SLES12 deployments (nginx install and lvm code)
