- aws/terraform/init-nodes.tpl
Remove references to `debug.sh` in AWS configuration
> Remove references to debug.sh in AWS configuration

- gcp/terraform/startup.sh
This fix adds a module needed for BYOS images to install missing packages.
> Add sle-module-public-cloud module for GCP instances

- aws/terraform/init-nodes.tpl
- azure/terraform/init-nodes.sh
- azure/terraform/provision/prepare_env.sh
- azure/terraform/provision/sshkeys.sh
Created a new script provision/sshkeys.sh with content from provision/prepare_env.sh and 4 lines from the install_hana() function to manage the nodes' ssh keys before the cluster setup.
A root password is no longer needed for setting up the cluster.
> Do not set a root password. SSH keys work

- gcp/terraform/startup.sh
Use VERSION_ID instead of VERSION.
The os-release(5) manpage states that VERSION may contain the release code name.
> Use VERSION_ID instead of VERSION

- aws/terraform/README.md
- aws/terraform/instances.tf
- aws/terraform/variables.tf
- Improvement for using a different AMI for iSCSI server.
- README update according to this change
- Change of default AMI to use SLES 15 instead of SLES 12SP3, it's just an update for default options.
> Add ami iscsi server

- libvirt/terraform/README.md
update readme relative links to default,hana_module and pillar under Salt modules section
> README update to correct links in Salt modules

- .travis.yml
- libvirt/terraform/main.tf
- libvirt/terraform/modules/base/main.tf
- libvirt/terraform/modules/base/variables.tf
- libvirt/terraform/modules/hana_node/main.tf
- libvirt/terraform/modules/hana_node/variables.tf
- libvirt/terraform/modules/host/main.tf
- libvirt/terraform/modules/host/variables.tf
- libvirt/terraform/modules/sbd/variables.tf
- libvirt/terraform/variables.tf
The libvirt Terraform configuration check was not added to Travis when the PR from @arbulu89 was made.
This PR adds the check and code reformatted by `terraform fmt`.
> Add libvirt to travis

- .travis.yml
- libvirt/terraform/main.tf
This commit makes travis check any new provider added to the repo, to guarantee that it is validated and given appropiate tests on the initial push. The travis script was also updated to take into account that
`terraform init` for libvirt will not work in travis as the terraform binary from hashicorp cannot automatically download the libvirt plugin, and that there is no remote-state.tf file in libvirt.
Libvirt's main.tf was also formatted per terraform v0.11.11.
> Expand travis check to any new provider

- azure/terraform/provision/hanasr.template
The HA order constraint for HANA should use the 'Mandatory' keyword instead of the current value of '1000'.
This is mandatory for newer version of Pacemaker, but also usable on previous version available on SLE-12-SP3+.
> Change 'order' constraint to not use deprecated one

- azure/terraform/network.tf
* Update deprecated `public_ip_address_allocation` in favor of `allocation_method` in Azure configuration files.
[Link ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2576)for upstream PR about this change
> Update deprecated function

- salt/install-salt-minion.sh
Install the salt-minion from the SUSE official Repository using
registration. 
This script can be used for provisioning machines or images that do not have a pre-installed salt-minion.
> Add install-salt-minion.sh

- gcp/terraform/README.md
- gcp/terraform/instances.tf
- gcp/terraform/startup.sh
- gcp/terraform/terraform.tfvars
- gcp/terraform/variables.tf
The `init_variable` supports:
- `all` (default: setup the cluster and install HANA)
- `skip-hana` (setup the cluster and don't install HANA)
- `skip-all` (don't do nothing)
> Add the init_type variable to setup the cluster without installing HANA

- libvirt/terraform/README.md
remove description about creating new ssh keys from readme, as now it is automated
> update readme about cluster ssh keys creation process

- .travis.yml
- gcp/terraform/README.md
- gcp/terraform/disks.tf
- gcp/terraform/instances.tf
- gcp/terraform/provision/google/README.md
- gcp/terraform/provision/google/alias
- gcp/terraform/provision/google/gcpstonith
- gcp/terraform/provision/google/route
- gcp/terraform/provision/google/sap_lib_ha.sh
- gcp/terraform/provision/google/sap_lib_hdb.sh
- gcp/terraform/provision/google/sap_lib_main.sh
- gcp/terraform/startup.sh
- gcp/terraform/terraform.tfvars
- gcp/terraform/variables.tf
Currently, the deployment depends on Google scripts and resource agents that are downloaded.  This PR adds these scripts to avoid that any upstream changes break our deployment.  We should instead merge those upstream changes when needed.
This PR also:
- Fixes a bug in the Google scripts for SLES 15.
- Adds support for 15SP1
- Uses smaller disks when not installing HANA
- Parameterizes SAP HANA backup size
> Add google scripts

- salt/pre_installation/ha_repos.sls
Grains information is different in old SLES12 version (sp1, sp2, sp3).
To solve that we need to use osmajorrelease instead of osfinger.
Anyway, this approach must be improved in the future to use the exact repository version.
By now, as the packages are not ready for old versions we can workaround with the current solution.
> Update repository selection conditions

- aws/terraform_salt/instances.tf
- salt/hana_node/download_hana_inst.sls
In SLES12SP3 (and older) version the aws-cli version doesn't work if region is not provided.
To fix that we will use the region in all the deployments as it works fine.
> Update aws cli usage adding the region option

- pillar_examples/automatic/cluster.sls
- pillar_examples/aws/cluster.sls
- pillar_examples/azure/cluster.sls
- pillar_examples/libvirt/cluster.sls
The IPaddr2 RA warns you if dotted quad netmask is used instead of the CIDR notation:
`IPaddr2(rsc_ip_PRD_HDB00)[10788]: WARNING: Please convert dotted quad netmask 255.255.0.0 to CIDR notation 16!`
> Change netmask form to avoid a warning

- gcp/terraform_salt/instances.tf
This PR fixes the issue about non-persistent hostname on GCP.
Custom hostnames must be defined in terraform since those configured by Salt aren't persistent.
For compatibility and readability purpose, the both method could be kept as they use the same variable.
> Fix hostname for GCP

- salt/pre_installation/ha_repos.sls
In some older releases (sles12sp3 in libvirt) the osmajorrelase
parameter is a string.
This might solve the issue with old salt versions (salt-call 2016.11.4 (Carbon) for example)
osfullname:
SLES
osmajorrelease:
12
osrelease:
12.3
osrelease_info:
- 12
- 3
**INFO: I was wondering why we didn't find this issue with cloud providers. The reason is, we install salt using other systems (install-saltminion.sh). In libvirt, we use the default salt version. This might create different problems as some feature are not available.
Maybe, we should consider to update salt to the last version before starting the provisioning**
> Cast osmajorrelease version to int

- salt/default/repos.sls
- salt/pre_installation/ha_repos.sls
The priorities work from ASC order, where 1 is the highest priority. With that, this PR adjust the priorities in order to:
1. Prefer the packages from the SUSE official repos (provided by Registration)
2. Prefer the packages from the HA/SAP salt packages repo
3. Prefer the Additional repos that can be included by the user.
This is considered by zypper in case the same package is provided by different repos.
> Fix the repos priorities to prefer the official repo packages first

- aws/terraform_salt/README.md
- aws/terraform_salt/terraform.tfvars.example
- aws/terraform_salt/variables.tf
- azure/terraform_salt/README.md
- azure/terraform_salt/terraform.tfvars.example
- azure/terraform_salt/variables.tf
- gcp/terraform_salt/README.md
- gcp/terraform_salt/terraform.tfvars.example
- gcp/terraform_salt/variables.tf
- libvirt/terraform/README.md
- libvirt/terraform/terraform.tfvars.example
- libvirt/terraform/variables.tf
- salt/pre_installation/ha_repos.sls
Improve the documentation and does not calculate the version anymore, as it can be misleading for the user to format the URL this way.
The natural instinct is to Copy and Paste the URL of the repository he wants to use.
> Change the format of the HA/SAP Salt packages Repo URL

- gcp/terraform/README.md
- gcp/terraform/disks.tf
- gcp/terraform/instances.tf
- gcp/terraform/terraform.tfvars.example
- gcp/terraform/variables.tf
This PR:
- Adds support for public images in GCP using `use_custom_image` variable.
- Fixes the name for iscsi-data.  It should contain the workspace as prefix.
> GCP: Support public images

- salt/default/init.sls
- salt/pre_installation/ha_repos.sls
The repositories refresh fails sometimes with 502 bad gateway error. In order to fix (or workaround) this error the retries are added.
> Add retry to repositories refresh to avoid 502 err

- libvirt/terraform/README.md
- libvirt/terraform/main.tf
- libvirt/terraform/modules/base/main.tf
- libvirt/terraform/modules/base/variables.tf
- libvirt/terraform/modules/host/main.tf
- libvirt/terraform/modules/sbd/main.tf
- libvirt/terraform/variables.tf
Until now the resources were not named using the workspace name. Now, `name_prefix` variable is changed to use the current workspace as in the other providers
> Update name_prefix by workspace name

- gcp/terraform_salt/disks.tf
iSCSI data disk should be prefixed with the workspace name like other resources.
> Fix iscsi-data disk name on GCE

- pillar_examples/automatic/cluster.sls
- pillar_examples/aws/cluster.sls
- pillar_examples/azure/cluster.sls
- pillar_examples/libvirt/cluster.sls
Based on the update in saphanabootstrap-formula related to update and renaming of resources template file, its usage needs to be updated in ha-sap-terraform-deployments project.
> Rename usage of resources template file

- libvirt/terraform/modules/host/main.tf
- libvirt/terraform/modules/iscsi_server/main.tf
- libvirt/terraform/outputs.tf
The new output is like:
```Apply complete! Resources: 9 added, 0 changed, 0 destroyed.
Outputs:
cluster_nodes_hostname = libvirt-sles12sp4-false-po-hana-1,libvirt-sles12sp4-false-po-hana-2
cluster_nodes_id = 36658331-795b-4480-880b-39bdeafb6dc8,7f1a5d9e-ee8d-47e1-b77a-970c68330a49
cluster_nodes_ip = 10.162.30.197,2620:113:80c0:80a0:10:162:30:d993,fe80::1c59:bff:fe4c:6adc,10.162.30.236,2620:113:80c0:80a0:10:162:31:c88d,fe80::845f:b2ff:fe8c:1da6
```
This way in the nodes ips only addresses are shown
> Improve libvirt output to show ip addresses

- salt/install-salt-minion.sh
In some cases we may need to force refresh the repos and the keys.
Keys may change during lifetime of this OS/image.
> Fix missing signed-keys in zypper

- salt/default/init.sls
- salt/default/repos.sls
Zypper refresh in Salt code is only executed on libvirt but it can be useful to do this on all cloud provider.
> Refresh zypper repos not only on libvirt

- gcp/terraform_salt/README.md
- gcp/terraform_salt/disks.tf
- gcp/terraform_salt/instances.tf
- gcp/terraform_salt/terraform.tfvars.example
- gcp/terraform_salt/variables.tf
We currently use the same image provided for SAP nodes for the iSCSI server, which is not really needed.
This commit modify this to use a public OS image, by default the SLES4SAP-15 image.
An improvement could be to use a non-SAP image but we will need to add/use another regcode for this image.
These changes have been successfully tested.
> Use public OS image on GCE

- salt/default/registration.sls
The grains function returns None and the comparison fails generating a
string "-e None" when the email is not informed.
> Fix the comparison when the reg email is not informed

- libvirt/terraform/README.md
- libvirt/terraform/doc/monitoring.md
- libvirt/terraform/main.tf
- libvirt/terraform/modules/monitoring/main.tf
- libvirt/terraform/modules/monitoring/variables.tf
- libvirt/terraform/variables.tf
- pillar_examples/automatic/cluster.sls
- pillar_examples/automatic/hana.sls
- pillar_examples/aws/cluster.sls
- pillar_examples/azure/cluster.sls
- pillar_examples/libvirt/cost_optimized/cluster.sls
- pillar_examples/libvirt/performance_optimized/cluster.sls
- salt/deployment.sh
- salt/hana_node/cluster_packages.sls
- salt/hana_node/hana_packages.sls
- salt/pre_installation/init.sls
- salt/pre_installation/minion_configuration.sls
- salt/pre_installation/packages.sls
Salt formula sates are installed in different path beyond sle15sp1.
Besides that, some hardcoded repository names has been removed, as the packages might come from packageHub now the salt formulas are released there.
> Update the pre configuration states to support sle15sp1 (and bugfixing)

- aws/terraform_salt/salt_provisioner.tf
- azure/terraform_salt/salt_provisioner.tf
- gcp/terraform_salt/salt_provisioner.tf
- libvirt/terraform/modules/iscsi_server/salt_provisioner.tf
- salt/default/pkgs.sls
Two minor fixes for:
+ fix the `repos` requirement in `pkgs.sls` with folder name *default*
+ Change start from `0` to `1` to make partition aligned, also use percentage instead of fixed position.
> Minor fixup for iscsi partitioning and default repo requirement.

- libvirt/terraform/doc/monitoring.md
- libvirt/terraform/main.tf
- libvirt/terraform/modules/hana_node/main.tf
- libvirt/terraform/modules/hana_node/variables.tf
- libvirt/terraform/modules/host/salt_provisioner.tf
- libvirt/terraform/modules/host/variables.tf
- libvirt/terraform/modules/monitoring/main.tf
- libvirt/terraform/modules/monitoring/variables.tf
- libvirt/terraform/terraform.tfvars.example
- libvirt/terraform/variables.tf
- salt/hana_node/init.sls
- salt/hana_node/monitoring.sls
- salt/monitoring/init.sls
- salt/monitoring/prometheus/prometheus.yml
- salt/monitoring/provisioning/datasources/prometheus_localhost.yml
- salt/top.sls
- add `node_exporter service` to each host. This can be disabled with `monitoring_enabled option`, by default is set to True (enabled). The rationale behind this is that we will need to have other exporter, so a monitoring_enabled will just install them. It is not fine_grained but I think it should be ok, also in future we might move the node_exporter etc to formulas when the pkg repository are morestable. So I think for moment is pretty ok.
- add a mechanism to monitor multiple service, monitored_services. We have a list of HOST:PORT.
see https://github.com/SUSE/ha-sap-terraform-deployments/pull/114/files#diff-20a93b26850139589fffe838def26807R41
- add repos pkg needed, also this `https://download.opensuse.org/repositories/server:/monitoring/SLE_15/` for monitoring
- add documentation …
> add node_exporter for nodes and sles15 only

- aws/terraform_salt/terraform.tfvars.example
- aws/terraform_salt/variables.tf
- azure/terraform_salt/terraform.tfvars.example
- azure/terraform_salt/variables.tf
- gcp/terraform_salt/terraform.tfvars.example
- gcp/terraform_salt/variables.tf
- libvirt/terraform/modules/iscsi_server/variables.tf
- libvirt/terraform/terraform.tfvars.example
- salt/default/registration.sls
- salt/hana_node/hana_packages.sls
- salt/iscsi_srv/init.sls
- salt/iscsi_srv/qa_iscsi.sls
Using "true" and "false" as a string could be misunderstand.
This PR changes qa_mode variable from a string to a boolean type.
**Tests:**
AWS: OK
Azure: OK
GCP: OK
> Change qa_mode as a boolean

- libvirt/variables.tf
I found out that the new terraform TF12 is more strict on variables.
In the libvirt CI we are passing qa_mode variable but this isn't defined/declared. 
TF12 is more strict on values and error out :(
```
11:40:24 Error: Value for undeclared variable
11:40:24 
11:40:24 A variable named "qa_mode" was assigned on the command line, but the root
11:40:24 module does not declare a variable of that name. To use this value, add a
11:40:24 "variable" block to the configuration.
11:40:24 
```
This pr will fix this problem on CI. It doesn't support qa-mode fully on libvirt, for this I don't have the time. But it is a good step to it for the future :)
> Declare qamode variable for libvirt

- libvirt/main.tf
- libvirt/modules/monitoring/main.tf
- libvirt/modules/monitoring/salt_provisioner.tf
- libvirt/modules/monitoring/variables.tf
- libvirt/outputs.tf
This PR is part of the RFC i wrote. (https://confluence.suse.com/pages/viewpage.action?pageId=302186655)
This PR will make the monitoring module indipendent from HANA/and host disks, so we don't have any dependency from other modules.
I will test this shortly and removing the WIP. Should work already but I will deploy for safety
fix #123
> Make monitoring module indipendent from host

- libvirt/modules/hana_node/salt_provisioner.tf
currently the variable develmode is set but is not injected via a grain (salt-provisioner.tf)
This pr fix this.
Also, I think that we don't need a global variable. We just make a variable belong to `hana_node` module and we set it to `main.tf`. 
In future we will need to remove this  but for moment let's get it working :)
> FIX: inject the develmode grain in salt-provisioner

- aws/README.md
- aws/salt_provisioner.tf
- aws/variables.tf
- azure/README.md
- azure/salt_provisioner.tf
- azure/variables.tf
- gcp/salt_provisioner.tf
- gcp/variables.tf
- libvirt/README.md
- libvirt/main.tf
- libvirt/modules/hana_node/salt_provisioner.tf
- libvirt/modules/hana_node/variables.tf
- libvirt/modules/iscsi_server/salt_provisioner.tf
- libvirt/modules/iscsi_server/variables.tf
- libvirt/modules/monitoring/salt_provisioner.tf
- libvirt/modules/monitoring/variables.tf
- libvirt/terraform.tfvars.example
- libvirt/variables.tf
- salt/default/repos.sls
we never used this variable and it can be tricky to manage.
An user can add always later additional repos after the deployment
I will test this PR just in case of but it should be already ok
> remove additional_repos variable

- aws/README.md
- gcp/README.md
As the provision symlink was removed, we need to update documentations about where to generate sshkeys.
> Fix sshkey documentation for AWS and GCP

- azure/instances.tf
- salt/pre_installation/ha_repos.sls
- salt/pre_installation/packages.sls
we had issues with devel_mode espcially with azure. but was a coincidence.
This pr will allow to safe update pkgs.
When we update the system in pre-install phase, this fix issues we have
encountered in Azure cloud, where the image had already some pkgs
installed like hawk-api-server.
If we now do a allow-vendor changes and zypper up in devel mode, if
there are already this pkgs we will update them, and fix the issues.
If the pkgs aren't installed, we will install them to latest since we allow the vendor changes.
> fix devel_mode for deployment

- azure/README.md
- azure/instances.tf
- azure/terraform.tfvars.example
- azure/variables.tf
When I was doing benchmark tests in Azure, I noticed that we don't use SSD as DATA disks in Azure like we are doing in other cloud providers.
This PR changes:
- Default DATA disks from `Standard_LRS` to `StandardSSD_LRS`.
Disk type could be set with `hana_data_disk_type` variable.
- New variable `hana_data_disk_caching` added to manage data disk caching.
Could be None, ReadOnly or ReadWrite (ReadWrite by default).
> Add option to set disk type and caching for HANA

- aws/README.md
- aws/salt_provisioner.tf
- aws/terraform.tfvars.example
- aws/variables.tf
- azure/README.md
- azure/salt_provisioner.tf
- azure/terraform.tfvars.example
- azure/variables.tf
- gcp/README.md
- gcp/salt_provisioner.tf
- gcp/terraform.tfvars.example
- gcp/variables.tf
- libvirt/README.md
- libvirt/main.tf
- libvirt/modules/hana_node/salt_provisioner.tf
- libvirt/modules/hana_node/variables.tf
- libvirt/terraform.tfvars.example
- libvirt/variables.tf
- salt/qa_mode/files/hwcct/hwcct_bench.jinja
- salt/qa_mode/files/hwcct/hwcct_config.json.jinja
- salt/qa_mode/init.sls
- salt/qa_mode/run_qa_mode.sh
- salt/salt_provisioner_script.tpl
This PR adds a possibility to execute HWCCT (Hardware Configuration Check Tool) in public cloud providers.
It's mainly a new feature for QA testing. The benchmark usually lasts about 2 hours with SSD drive.
The purpose is to execute it when we are doing build validation.
Results will be both in /root/hwcct_out and in the global log file /tmp/provisioning.log
Tested with an without hwcct set to true:
> Add hwcct benchmark

- salt/hana_node/init.sls
- salt/hana_node/network.sls
This PR fixes bsc#1144282 for AWS and Azure.
No impact for GCP and libvirt.
> Fix CLOUD_NETCONFIG for IPaddr2

- salt/hana_node/monitoring.sls
- salt/monitoring/prometheus/prometheus.yml
- salt/monitoring/prometheus/rules.yml
This PR rely on the new ha metrics exporter defined here: 
`https://github.com/MalloZup/ha_cluster_exporter`
This export cluster metrics. From this we create alerts and dashboards.
- Add a 1st useful alert when, in our case when the master resource is down we will have an alert.  This is 
- Add needed configuration for enabling alerts in prometheus.
- This alert rely on the new `ha_metrics_exporter` which we need pkg first
> WIP: Add alerts for ha-metrics

- aws/README.md
- aws/instances.tf
- aws/terraform.tfvars.example
- aws/variables.tf
- gcp/README.md
- gcp/disks.tf
- gcp/terraform.tfvars.example
- gcp/variables.tf
This PR standardizes data disk usage for HANA:
For all public cloud providers:
- same variable `hana_data_disk_type`
- README file
- tfvars.example file
> Standardize data disk variables

- azure/provider.tf
Workaround for #188
Tested this morning in Azure with custom image.
> Fix azurerm provider version <= 1.33

- salt/qa_mode/init.sls
if `hwcct` variable is set to `false`, then `qa_mode/init.sls` is executed as an empty file, and so Salt exits with a `RC != 0`.
This commit fix it by adding a `test.nop` if `hwcct=false`.
Successfully manually tested on AWS.
> Fix HWCCT bench if 'hwcct=false'

- azure/monitoring.tf
- azure/salt_provisioner.tf
- doc/monitoring.md
- libvirt/main.tf
- libvirt/terraform.tfvars.example
- libvirt/variables.tf
Addresses #190.
The `monitored_hosts` variable is now just an internal detail of the `monitoring` module (in libvirt).
For the time being, it has also been removed entirely from the Azure provisioning (except in the salt grain), but it will probably be reintroduced as a module input variable later.
> remove `monitored_hosts` var from the outer layer of the tf config API

- azure/network.tf
- salt/monitoring/prometheus/prometheus.yml
previously it was the hawk-exporter (deprecated)
now the ha-cluster exporter is running on port 9002
> The port of ha-exporter has changed to 9002 and remove superficial if

- azure/monitoring.tf
- azure/terraform.tfvars.example
- doc/monitoring.md
- libvirt/modules/hana_node/variables.tf
- libvirt/terraform.tfvars.example
As `monitoring_srv_ip` is a mandatory variable and there is no default value. We must add it in `terraform.tfvars.example`.
Otherwise, terraform will ask for value:
```
var.monitoring_srv_ip
monitoring server address
Enter a value
```
I could do the same for libvirt but I found something incompatible:
[Monitoring](https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/doc/monitoring.md) doc says `monitoring_enabled default True.`
In libvirt, `monitoring_enabled `default is false.
@arbulu89 @MalloZup WDYT?
> Add monitoring doc in tfvars.example

- salt/hana_node/monitoring.sls
this pr will allow us to export systemd metrics about services.
I have checkd also with the #monitoring channel that the sysconfig and the way we activate the node_exporter is the right one.
There is also bug in the node_exporter pkg which I will fix it regarding the sysconfig conf, but unrelated to this pr
Tested pr works nice
> Node exporter/systemd metrics activation

- salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
- salt/monitoring/provisioning/dashboards/ha-sap-hana-detailed-timestamp.json
- Add systemd service in timestamped dashboard
- Correct duplicata service in cluster status dashboard
1) - Add systemd service in timestamped dashboard - This is a new graph
2) The second change is more a cosmetical thing. We had before 2 node exporter pannels, now we have only 1
> Update dashboards with graphs

- aws/README.md
- aws/instances.tf
- aws/monitoring.tf
- aws/network.tf
- aws/outputs.tf
- aws/salt_provisioner.tf
- aws/terraform.tfvars.example
- azure/terraform.tfvars.example
- doc/monitoring.md
- Enable monitoring for AWS
- Add the option to enable/disable monitoring for AWS
> Add monitoring logic to aws

- doc/monitoring.md
- gcp/README.md
- gcp/disks.tf
- gcp/instances.tf
- gcp/monitoring.tf
- gcp/network.tf
- gcp/outputs.tf
- gcp/salt_provisioner.tf
- gcp/terraform.tfvars.example
Enable monitoring for GCP with an option to disable it
GCP documentation needs to be rework as is in AWS or Azure (future PR).
> Add monitoring to GCP

- libvirt/modules/hana_node/main.tf
- libvirt/modules/iscsi_server/main.tf
- libvirt/modules/monitoring/main.tf
- libvirt/outputs.tf
Unify the terraform outputs for libvirt
This the output example:
```
cluster_nodes_ip = [
"192.168.145.2",
"192.168.145.3",
]
cluster_nodes_name = [
"libvirt-sles15-false-po-hana-1",
"libvirt-sles15-false-po-hana-2",
]
cluster_nodes_public_ip = [
"10.162.31.1",
"10.162.30.247",
]
cluster_nodes_public_name = []
iscsisrv_ip = [
"192.168.145.20",
]
iscsisrv_name = [
"libvirt-sles15-false-po-iscsi",
]
iscsisrv_public_ip = [
"10.162.32.61",
]
iscsisrv_public_name = []
monitoring_ip = [
"192.168.145.21",
]
monitoring_name = [
"libvirt-sles15-false-po-monitoring",
]
monitoring_public_ip = [
"10.162.31.12",
]
monitoring_public_name = []
```
> Unify outputs with cloud providers in libvirt

- aws/outputs.tf
- azure/outputs.tf
`output.tf` file is not consistent across each providers.
This commit fixes this and also add some information.
This is needed to be able to use this project in our Public Cloud tests in openQA.
Tested on AWS, GCP and Azure.
I can't test on libvirt, so if anyone can check if it's good a relevant.
EDIT: libvirt modifications have been removed, to different, will be done in another PR
EDIT2: GCP change is handled in @juadk 's PR #219.
> Add informations and fix 'output.tf'

- .ci/validate-terraform.sh
- .travis.yml
- pillar_examples/automatic/hana.sls
- pillar_examples/aws/cluster.sls
- pillar_examples/aws/hana.sls
- pillar_examples/azure/cluster.sls
- pillar_examples/azure/hana.sls
- pillar_examples/libvirt/cost_optimized/cluster.sls
- pillar_examples/libvirt/cost_optimized/hana.sls
- pillar_examples/libvirt/performance_optimized/cluster.sls
- pillar_examples/libvirt/performance_optimized/hana.sls
- salt/hana_node/download_hana_inst.sls
- salt/hana_node/formula.sls
- salt/hana_node/mount.sls
- salt/hana_node/sap_inst.sls
- salt/hana_node/ssh.sls
- salt/iscsi_srv/qa_iscsi.sls
- salt/top.sls
This PR adds two jobs to the Travis config to perform `jsonlint` and `salt-lint` on `.json` and `.sls` files respectively.
It also consequently applies linting to the salt files, which did not comply with the default linter rules.
> Add some linters to the CI

- salt/monitoring/prometheus/rules.yml
- salt/monitoring/provisioning/dashboards/ha-sap-hana-detailed-timestamp.json
This PR changes the disk usage statistics presentation as illustrated.
Before:
After:
> add system-wide disk usage statistics and update previous panel accordingly

- salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
This is a proposal for visualizing our new metric fail_count and threshold migration . See https://github.com/ClusterLabs/ha_cluster_exporter/pull/71
You can play with:
http://10.162.30.114/d/Q5YJpwtZk1/ha-sap-hana-cluster-status?orgId=1
___
> Add dashboard with failcount and threshold migr

- pillar_examples/automatic/cluster.sls
Value has been changed from `join_timer` to `wait_for_initialization`.
https://github.com/SUSE/habootstrap-formula/pull/30
`join_timer` is not used anywhere else.
Default value is 20 anyway.
> Remove pillar entry as name has been changed

- doc/monitoring.md
- salt/monitoring/prometheus/prometheus.yml
- salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
- Add documentation
- Modify prometheus config accordingly
- adapt dashboard to reflect change with multi-cluster
http://10.162.31.91/d/Q5YJpwtZk1/ha-cluster-status?orgId=1&refresh=5s
See the botton in the top `hacluster` where you can switch
> Enable multi-cluster for hacluster (dashboard and configuration in prometheus) + doc

- salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
- 1) hide an internal grafana variable (IP) since is rendundant
-  2) move clustername variable at left begin of dashboard since is more highlevel
> Improve layout of ha-dashboard

- salt/monitoring/prometheus/rules.yml
I might need to test this later on.
I couldn't figure out how we can add a generic alert for all resource so it is better to make a specific one and sys-admin can adapt on this showcase
> Add alert showcase for failcount threshold

- aws/terraform.tfvars.example
- azure/terraform.tfvars.example
- gcp/terraform.tfvars.example
- libvirt/terraform.tfvars.example
- pillar_examples/automatic/cluster.sls
- pillar_examples/aws/cluster.sls
- pillar_examples/azure/cluster.sls
- pillar_examples/libvirt/cost_optimized/cluster.sls
- pillar_examples/libvirt/performance_optimized/cluster.sls
A quick PR to adapt the pillar files to work with the latest salt formulas.
To make you see which is the requirement for sle12 version mainly.
> Update pillar files to work with latest salt formulas

- aws/outputs.tf
- aws/salt_provisioner.tf
- azure/instances.tf
- azure/network.tf
- azure/outputs.tf
- azure/salt_provisioner.tf
- gcp/outputs.tf
- gcp/salt_provisioner.tf
- libvirt/main.tf
- libvirt/modules/monitoring/main.tf
- libvirt/modules/monitoring/salt_provisioner.tf
- libvirt/modules/monitoring/variables.tf
- libvirt/outputs.tf
This PR simplifies HCL code that treats monitoring resources as multiple, because we actually support only one single Prometheus/Grafana host.
All monitoring related resources are now consistently looked up via the `0` index, and the outputs are strings instead of tuples.
> simplify monitoring resource references

- aws/salt_provisioner.tf
- azure/salt_provisioner.tf
- gcp/salt_provisioner.tf
- libvirt/modules/hana_node/salt_provisioner.tf
- libvirt/modules/iscsi_server/salt_provisioner.tf
- libvirt/modules/netweaver_node/salt_provisioner.tf
After pulling the latest updates, running any `terraform` command (including destroy)  on existing deployments will fail with the following:
```
Error: Invalid count argument
on modules/netweaver_node/salt_provisioner.tf line 15, in resource "null_resource" "netweaver_node_provisioner":
15:   count = var.provisioner == "salt" ? length(libvirt_domain.netweaver_domain) : 0
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```
This is due to the `libvirt_domain.netweaver_domain` resource not being initialized.
Using the `netweaver_count` var directly fixes the problem and allows to …
> Fix count argument backwards compat

- azure/salt_provisioner.tf
- gcp/salt_provisioner.tf
Fix ssh connection to monitoring provisioner in azure.
PD: The change in gcp is just to have same syntax
> Fix ssh connection to monitoring provisioner in azure

- aws/outputs.tf
- azure/outputs.tf
- gcp/outputs.tf
- libvirt/modules/monitoring/main.tf
I couldn't find a way to use the native `coalesce` function, so it's not super fancy, but these kind of quirks are the things that using `count` involves, so I totally blame Terraform for this. :grin:
> fix monitoring outputs by coalescing the resources with a count

- salt/monitoring/prometheus/rules.yml
- salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
This PR fixes a couple of alerts that were recently broken by to ClusterLabs/ha_cluster_exporter#96 and adds a new Prometheus alert and a Grafana dashboard panel for the resources constraints:
> Update alerts and add resource constraints panel

- doc/monitoring.md
- pillar_examples/automatic/drbd/drbd.sls
- salt/drbd_node/custom_handlers.sls
- salt/drbd_node/files/notify-split-brain-haclusterexporter-suse-metric.sh
- salt/drbd_node/init.sls
This PR add :
1) documentation for the splitbrain handler.
2) By default we set to the pillars https://github.com/SUSE/ha-sap-terraform-deployments/pull/266/files#diff-8e808cd5eda64f32034e6f8c362eecbaR69 that we want to use our handler
3) it implement the basic custom handler which create a temp file
4) We install this handler via saltstack for each node.
I tested this pr works fine
> Add DRBD handler mechanism for splitbrain metrics

- salt/netweaver_node/files/pillar/netweaver.sls
Updating the Netweaver pillar file to make master password common for all instances, and add optionally the `<sid>adm` password and `<sap>adm` password for all instances.
This is related to NW formula changes to passwords : https://github.com/SUSE/sapnwbootstrap-formula/pull/19
> Add sapadm and sidadm passwords &

- salt/default/repos.sls
The last workaround has an error if the `/etc/SUSEConnect` file doesn't exist;
```     Comment: Command "rm /etc/SUSEConnect && /
rm -f $(ls /etc/zypp/{repos,services,credentials}.d/* | grep -v -e 'ha-factory' -e 'server_monitoring') && /
rm -f /usr/lib/zypp/plugins/services/* && /
sed -i '/^# Added by SMT reg/,+1d' /etc/hosts && /
/usr/sbin/registercloudguest --force-new && /
zypper --non-interactive --gpg-auto-import-keys refresh
" run
Started: 14:45:45.406444
Duration: 7096.128 ms
Changes:   
----------
pid:
7140
retcode:
0
stderr:
/bin/bash: /: Is a directory
/bin/bash: line 1: /: Is a directory
/bin/bash: line 2: /: Is a directory
/bin/bash: line 3: /: Is a directory
```
> Fix command that creates issues if file does not exist

- .gitattributes
As there is a dependency on Unix style line endings due to the way Salt config files are assembled, I'd suggest to set the line endings style as part of the repository during initial clone/checkout (https://git-scm.com/docs/gitattributes#Documentation/gitattributes.txt-Settostringvalueauto). Otherwise git may by default change to CRLF under Windows.
> Add .gitattributes to fix EOL under Windows 

- azure/network.tf
Since the template deploys a HANA DB instance 00, HANA ports need to follow the instance number: 3xx13, 3xx14, 3xx15, 3xx17 where xx is the instance number. Same for health probe, which is 625xx. 
Rules in the template were originally for instance 03.
Also updated to use Accelerated Networking for HANA nodes (https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli)
> Fix LB rules to match SAP instance 00

- salt/monitoring/prometheus/prometheus.yml
Collecting metrics every 5s seconds can put unnecessary load into the
database
> Change the default HANA scraping time to 30s

- azure/main.tf
- azure/modules/netweaver_node/main.tf
- azure/modules/netweaver_node/variables.tf
- azure/network.tf
- azure/variables.tf
Remove some Netweaver and HANA hardcodes and move the options to variables to give the possibility to the user to set them.
All of the variables assume as default the values that were hardcoded before.
> Move some Netweaver and HANA OS and Network configurations to variables

- salt/monitoring/provisioning/dashboards/ha-sap-hana-detailed-timestamp.json
Include the HANA alerts from the database in a specific section and table on the top of the dashboard and remove the HA metrics that don't fit in the current dashboard context.
> Include HANA Alerts table and remove HA panels

- salt/monitoring/prometheus/rules.yml
It will raise an alert for each alert raised by HANA that is higher than 3 and what actions the user needs to take in order to solve that.
> Includes an alert in case HANA raises alerts with rating higher than 3

- salt/monitoring/provisioning/dashboards/cluster-status-real-time-alerts.json
Some of the corosync-related queries were not correctly set as instant so this would cause some panels to not be updated correctly.
> Fix some Grafana instant queries in HA Cluster dashboard

- pillar_examples/automatic/drbd/cluster.sls
- pillar_examples/automatic/hana/cluster.sls
- pillar_examples/aws/cluster.sls
- pillar_examples/azure/cluster.sls
- pillar_examples/libvirt/cost_optimized/cluster.sls
- pillar_examples/libvirt/performance_optimized/cluster.sls
- salt/drbd_node/files/templates/drbd_cluster.j2
- salt/netweaver_node/files/pillar/cluster.sls
Use the new `cloud_provider` parameter. I think eventually we could completely remove the provider usage in the project with some restructuration.
Depends on:
SUSE/habootstrap-formula#38
https://github.com/SUSE/habootstrap-formula/pull/38/files#diff-ede8388134830516402a39e126add733R6
> Update cluster pillar files to remove platform

- salt/default/update.sls
- salt/pre_installation/packages.sls
The deployment fails in the `update` command due: 
```
Do you agree with the terms of the license? [yes/no] (no): no
Aborting installation due to the need for license confirmation.
Please restart the operation in interactive mode and confirm your agreement with required licenses, or use the --auto-agree-with-licenses option.
```
This change accepts the license
> Accept the license during update

- salt/monitoring/prometheus/rules.yml
Fix jinja rendering in prometheus rules file: 
```
null_resource.monitoring_provisioner[0] (remote-exec): [ERROR   ] Rendering exception occurred
null_resource.monitoring_provisioner[0] (remote-exec): Traceback (most recent call last):
null_resource.monitoring_provisioner[0] (remote-exec):   File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
null_resource.monitoring_provisioner[0] (remote-exec):     output = render_str(tmplstr, context, tmplpath)
null_resource.monitoring_provisioner[0] (remote-exec):   File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 412, in render_jinja_tmpl
null_resource.monitoring_provisioner[0] (remote-exec):     tmplstr)
null_resource.monitoring_provisioner[0] (remote-exec): SaltRenderError: Jinja syntax …
```
> Fix jinja rendering for the prometheus alert rules

- salt/monitoring/prometheus/prometheus.yml
don't set ha_cluster_exporter prometheus targets for netweaver nodes that are not part of a HA cluster
fixes #301
> Fix Netweaver prometheus config

- README.md
- aws/terraform.tfvars.example
- aws/variables.tf
- azure/terraform.tfvars.example
- azure/variables.tf
- gcp/terraform.tfvars.example
- gcp/variables.tf
This PR changes all instance type default value to systems certified by SAP.
Recommendations found [here](https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/iaas.html#) (Certified and supported SAP HANA Hardware Directory)
I choose systems with filter `Clustering = yes`
**AWS**:
r3.8xlarge - [SAP Certified IaaS Platforms for AWS](https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/iaas.html#categories=Amazon%20Web%20Services)
**GCP**:
n1-highmem-32 - [SAP Certified IaaS Platforms for GCP](https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/iaas.html#categories=Google%20Cloud%20Platform)
**Azure**: 
Standard_M128s - [SAP Certified IaaS Platforms for Azure](https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/iaas.html#categories=Microsoft%20Azure)
TODO:
> Change instance type for SAP certified systems

- salt/pre_installation/registration.sls
The `if` statement is wrong. With this fix if `qa_mode` is set to `True` the the iscsi server will continue being registered but any node related to HA or SAP won't (hana, drbd and netweaver nodes).
> Fix registration check (remove .*)

- azure/README.md
Update readme to change example workspace name to avoid such errors. Azure resource name can only consist of lowercase letters and numbers
```
Error: name can only consist of lowercase letters and numbers, and must be between 3 and 24 characters long
on resources.tf line 6, in resource "azurerm_storage_account" "mytfstorageacc":
6: resource "azurerm_storage_account" "mytfstorageacc" {
```
> Update readme to change example workspace name

- azure/README.md
- azure/main.tf
- azure/modules/drbd_node/main.tf
- azure/modules/drbd_node/variables.tf
- azure/modules/hana_node/main.tf
- azure/modules/hana_node/variables.tf
- azure/modules/iscsi_server/main.tf
- azure/modules/iscsi_server/variables.tf
- azure/modules/monitoring/main.tf
- azure/modules/monitoring/variables.tf
- azure/terraform.tfvars.example
- azure/variables.tf
As most of the VM sizes `(vm_size)` in Azure were hardcoded, this PR makes them configurable, for terraform modules (drbd, hana, scsi server, netweaver, monitoring)
Also updating the different variable names (instance_type, instancetype, vm_size) to use one name ie `vm_size`
> Make Azure VM sizes configurable for all terraform modules

- aws/README.md
Add an empty line before code to ease reading of the Markdown source and keep current formatting while there.
> Fix internal broken links

- pillar_examples/README.md
Polish the pillar example and add index to SAP HANA/DRBD cluster, to avoid forget copy DRBD pillars in a full(HANA/NW/DRBD) deployment.
> Move DRBD pillar example together with hana example.

- README.md
- doc/saptune.md
- pillar_examples/automatic/hana/hana.sls
- pillar_examples/aws/hana.sls
- pillar_examples/azure/hana.sls
- pillar_examples/libvirt/cost_optimized/hana.sls
- pillar_examples/libvirt/performance_optimized/hana.sls
- salt/netweaver_node/files/pillar/netweaver.sls
This PR is a follow-up for the previous work on the saptune module in salt. It enables the mechanism to apply to all node a saptune solution.
For reference look at prs:
- saptune module implementation https://github.com/SUSE/salt-shaptools/pull/45 ( shaptools)
- https://github.com/SUSE/sapnwbootstrap-formula/pull/27 (netweaver formula enablement)
- https://github.com/SUSE/saphanabootstrap-formula/pull/65 (hana formula enablement )
This pr , with the new tfvars
`saptune_solution = "HANA"` will allow to apply to all node the saptune solution (in this case) HANA.
So that the user can choose which saptune solution can apply to all (netweaver and ha) cluster nodes .
> adapt pillars of deployment to apply saptune solutions

- pillar_examples/README.md
Adding info and links to the salt pillar encryption
Does the current Readme location makes sense? 
Should we provide the pros/cons on using gpg keys in current approach as I did?
> Add documentation info on salt pillar encryption

- salt/deployment.sh
- salt/formula.sh
- salt/netweaver_node/nfs.sls
- salt/pre_installation/minion_configuration.sls
- salt/top.sls
This PR fixes 2 issues:
- `mount_sapmnt` is used in the `sapnwbootstrap-formula`, so we need to change the name to avoid duplicated states
- In order to keep idempotency properly, we need to split the execution of the formulas and the pre deployment. This is done having different salt envs that are executed in the highstate.
Before that, the `iscsi_srv` execution was failing because the `file_root` variable was not getting the folder where iscsi formula states are stored.
I have tested with AWS and works fine now.
> Fix salt scripts usage to run the proper top files

- README.md
- azure/modules/hana_node/variables.tf
- azure/terraform.tfvars.example
- azure/variables.tf
This PR changes default instance for Azure and adds links about certified systems in documentation.
Azure warned us about the default instance we are using in the project.
They told to use smaller instance which is also supported.
We chose M128S because it is a recommended instance for clustering but Azure told us that clustering means for scale-out scenario and not HA clustering.
> Change default instance for azure

- aws/README.md
- aws/instances.tf
- aws/terraform.tfvars.example
- aws/variables.tf
- salt/cluster_node/iscsi_initiator.sls
- salt/pillar/iscsi_srv.sls
Fix issue#357 and issue#258
Remove the hard code of instance type of iscsi/monitoring nodes, since it is different per region.
Correct the queue_depth configuration of iscsi pillar file.
> Fix iscsi queue_depth configuration error and hard code of instance type of iscsi/monitoring nodes on aws

- salt/monitoring/provisioning/dashboards/netweaver-cluster-status.json
- this pr add an initial dashboard + Process table of process.
- It add also the needed grafana variables like `node_name` etc which we use in other dashboards etc
> Grafana/dashboard: Add initial process table for netweaver

- aws/modules/netweaver_node/variables.tf
- aws/modules/sap_cluster_policies/variables.tf
- aws/monitoring.tf
- aws/variables.tf
- azure/modules/drbd_node/variables.tf
- azure/modules/hana_node/variables.tf
- azure/modules/iscsi_server/variables.tf
- azure/modules/monitoring/variables.tf
- azure/modules/netweaver_node/variables.tf
- azure/variables.tf
- gcp/modules/drbd_node/variables.tf
- gcp/modules/netweaver_node/variables.tf
- gcp/monitoring.tf
- gcp/variables.tf
- libvirt/modules/drbd_node/variables.tf
- libvirt/modules/hana_node/variables.tf
- libvirt/modules/iscsi_server/variables.tf
- libvirt/modules/monitoring/variables.tf
- libvirt/modules/netweaver_node/variables.tf
- libvirt/variables.tf
Hello,
I have noticed that when the variables are passed through the command line to terraform, the boolean types are not properly managed.
I was running `terraform plan -var "drbd_enabled=false" -var "netweaver_enabled=true" -var "monitoring_enabled=false"` command, and the new entries are not set as boolean, or something strange happens. It looks kind a bug.
Anyway, setting the type to the variables fixes the issue
PD: I have moved some variables from `monitoring.tf` to the main `variables.tf` file where they should belong to
> Set type bool entry to boolean type variables

- salt/cluster_node/iscsi_initiator.sls
Somehow, enable iscsid service may cause iscsi don't
automatical login after disconnecting for any reason,
which need to restart iscsid to fix.
Error log:
iscsid: Kernel reported iSCSI connection 1:0 error
(1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed)
This issue can not reproduce on libvirt, only in AWS/Azure.
> Fix iscsi initiator cannot automatic login after disconnected.

- aws/terraform.tfvars.example
- aws/variables.tf
- azure/modules/hana_node/variables.tf
- azure/terraform.tfvars.example
- azure/variables.tf
- gcp/terraform.tfvars.example
- gcp/variables.tf
- libvirt/modules/netweaver_node/variables.tf
- libvirt/variables.tf
- pillar_examples/automatic/netweaver/netweaver.sls
- pillar_examples/aws/hana.sls
- pillar_examples/azure/hana.sls
- pillar_examples/libvirt/cost_optimized/hana.sls
- pillar_examples/libvirt/performance_optimized/hana.sls
- salt/netweaver_node/installation_files.sls
We have found out that the usage of the `/root` folder to store HANA installation software is not really good idea.
The installer complains of having invalid permissions if the used HANA installation is obtained from a SAR file if the files are in `/root` folder.
In order to avoid that, the easy solution is just to have a different default value.
`/hana_inst_media` just works fine, but other options could be good as well.
My unique doubt is if this could have some security risk (I cannot find any).
> Update hana_inst_folder default value

- aws/README.md
- aws/instances.tf
- aws/main.tf
- aws/modules/netweaver_node/main.tf
- aws/modules/netweaver_node/variables.tf
- aws/modules/sap_cluster_policies/main.tf
- aws/modules/sap_cluster_policies/variables.tf
- aws/terraform.tfvars.example
- aws/variables.tf
Remove `aws_account` explicit usage. It was created to use in the policies creation, but terraform already has a native way to obtain that information.
**Merging directly to master, as it would help to run some tests in openQA. I will create `4.1.0` version only with this change.**
> Get aws_account data automatically from terraform

- aws/variables.tf
When I brought change from Master to develop in https://github.com/SUSE/ha-sap-terraform-deployments/commit/5d91553b44ae9d5ecaf707622c633d447e70fc9a
I failed editing the conflicts..
In fact, as I did the merge manually to avoid more PRs, the CI was not executed.
Maybe in the future, we should do proper merge requests to sync develop with master
> Remove duplicated variables from aws variables

- azure/infrastructure.tf
This PR fixes issue #188  which is freezing azurerm provider version to 1.33, I did a test with azurerm version number 1.44 and everything works as expected for provisioning infrastructure.
> Fix issue #188

- aws/terraform.tfvars.example
- azure/terraform.tfvars.example
- gcp/terraform.tfvars.example
- libvirt/terraform.tfvars.example
- pillar_examples/automatic/hana/hana.sls
I have done a change to update the usage of the `software_path` entry in HANA pillar file.
Before this, the code war forcing to download the whole folder where HANA folder was stored. This might not be optimal, as many HANA versions might be stored there, and they are really heavy. We don't most probably want to download them all.
Now we can have the next 2 options:
```
hana_inst_media = "url-to-your-nfs-share:/sapdata/sap_inst_media/51053381"
```
Where you only get the HANA folder.
Or, where you can get the whole folder and choose the platform directory
```
#hana_inst_media = "url-to-your-nfs-share:/sapdata/sap_inst_media"
#hana_platform_folder = "51053381"
```
> Improve software_path usage to only download HANA folder if desired

- aws/salt_provisioner.tf
- azure/main.tf
- libvirt/main.tf
- pillar_examples/automatic/netweaver/cluster.sls
This PR changes Prometheus configuration to use floating ips as target of the netweaver exporters.
It also introduces the `monitoring_enabled` variable in the netweaver pillar, which was missing and is leveraged by SUSE/sapnwbootstrap-formula#43
> update prometheus nw targets

- salt/provision.sh
A fix for the `argument_number` variable usage. I thought that the `OPTIND` was the argument count of the number, but it's not, even though it might work in some conditions...
With this change the count is done manually (i have not found any native way with `getopt`).
> Fix argument_number usage

- salt/drbd_node/files/templates/drbd_cluster.j2
Update load-balancer resource agent.
I have kept the `rsc_socat` nomenclature as in SUSE distros it uses socat instead `nc`, so it makes sense (replacing by `nc` as the guide suggests is confusing)
https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability
> Update anything resource by azure-lb in drbd template

- salt/cluster_node/templates/aws_credentials_template.j2
The current code implies to have space around the `=` sign for `aws_access_key_id` and `aws_secret_access_key` variables in `${HOME}/.aws/config`.
This is not mandatory and could lead to issues during deployment (VIP not working for example).
Backport of this commit from `develop` to `master` to be able to create a `4.1.1` release.
> Fix AWS credential file

- salt/drbd_node/files/templates/drbd_cluster.j2
A duplicated `{%- if cloud_provider == "microsoft-azure" %}` was added in the DRBD ha template (most probably resolving some conflicts).
This PR fixes that error
> Remove duplicated condition in drbd ha template

- aws/infrastructure.tf
- aws/modules/netweaver_node/main.tf
- aws/modules/sap_cluster_policies/main.tf
- aws/modules/sap_cluster_policies/templates/aws_stonith_policy.tpl
- azure/infrastructure.tf
Remove the `template` provider usage as we can use the new feature in terraform 12 `templatefile`.
`templatefile` has the benefit that it can pass lists to be rendered. This is important, as otherwise we were always assuming that we had 2 elements to be rendered, what if you want to deploy a single hana, was causing errors.
> Improve template usage in aws policies

- libvirt/main.tf
- libvirt/variables.tf
These variables configure the machine capabilities.
The list is:
hana_node_vcpu
hana_node_memory
hana_node_disk_size
iscsi_vcpu
iscsi_memory
sbd_disk_size
monitoring_vcpu
monitoring_memory
netweaver_node_vcpu
netweaver_node_memory
netweaver_shared_disk_size
drbd_node_vcpu
drbd_node_memory
drbd_disk_size
drbd_shared_disk_size
> Added variables to libvirt provider

- gcp/main.tf
- gcp/modules/drbd_node/salt_provisioner.tf
- gcp/modules/hana_node/salt_provisioner.tf
- gcp/modules/iscsi_server/salt_provisioner.tf
- gcp/modules/netweaver_node/salt_provisioner.tf
- gcp/terraform.tfvars.example
- gcp/variables.tf
- pillar_examples/automatic/drbd/drbd.sls
- salt/hana_node/download_hana_inst.sls
- salt/netweaver_node/installation_files.sls
Storage devices in GCE are currently set either in the tfvars file or hardcoded in TF/sls files. This is bad because device name in Linux are handled by udev and the naming is dynamic (`/dev/sdb` could be `/dev/sda` sometimes).
This commit removes all of these by using GCE functionalities to get the correct device name.
Manual tests done successfully and through [openQA tests](http://1b210.qa.suse.de/tests/6633) also.
> Remove hardcoded storage devices on GCE

- salt/monitoring/provisioning/dashboards/ha-cluster-details.json
- salt/monitoring/provisioning/dashboards/multi-cluster-overview.json
This PR addresses BC breaking changes that will be introduced by ClusterLabs/ha_cluster_exporter#152.
It also overhauls the "HA Cluster Details" dashboard by introducing some new graphs to track node and resource statuses, as shown in this screenshot:
Demo [here](http://10.162.30.4/d/Q5YJpwtZk1/ha-cluster-details)
The DRBD and Alerts panels were removed for now, mainly because they didn't add much value as they were, and another way of handling that information is being explored.
This also fixes #315
> Update HA cluster dashboards

- salt/os_setup/registration.sls
Remove PackageHub extension installation, as we don't need it any more (the gcp cloud packages are available in the cloud extension).
This change is important, as we don't need to use the `devel_mode` flag any longer to make the deployment work.
> Remove PackageHub extension

- libvirt/modules/netweaver_node/salt_provisioner.tf
- pillar_examples/automatic/netweaver/cluster.sls
- salt/cluster_node/iscsi_initiator.sls
Fixes:
- `lsscsi` package is not always available, so we need to install it (I have put it in the iscsi initiator, as it's only used together with iscsi, and the call is just in this scenario)
- In libvirt, netweaver doesn't use iscsi by now, so `shared_storage_type` variable doesn't exist. In the future, if we include the iscsi usage in netweaver to use sbd and netweaver shared folder, we might implement this. By now, a shared disk created by libvirt is always used.
> Install lsscsi and use nw grains properly

- libvirt/modules/drbd_node/main.tf
- libvirt/modules/hana_node/main.tf
- libvirt/modules/iscsi_server/main.tf
- libvirt/modules/monitoring/main.tf
- libvirt/modules/netweaver_node/main.tf
- libvirt/outputs.tf
We set the hostnames via salt states so there is no need to use the libvirt field, which in some cases it's even wrong and wouldn't match the actual hostname set by salt.
I manually tested this and it has no effect whatsoever.
supersedes #291
> remove libvirt network hostname fields

- pillar_examples/automatic/hana/cluster.sls
Update cluster tuning for Azure to follow the configuration provided in:
https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#default-pacemaker-configuration-for-sbd
Now, sbd resource parameters,  cluster properties, rsc_defaults and op_defaults can be updated.
@diegoakechi Eventually we would want to drop the defaults configuration done in the formulas templates, as it is really inflexible. Having the option to make changes from the pillar file it's better in my opinon.
Depends on:
https://github.com/SUSE/salt-shaptools/pull/63
https://github.com/SUSE/habootstrap-formula/pull/49
bsc#1170702
> Update cluster pillar file for azure for better tuning

- aws/main.tf
- azure/main.tf
- gcp/main.tf
- libvirt/main.tf
The HANA monitored address was incorrect for non HA scenarios.
We need to adapt the used IP as the monitored address is the last one in the list.
https://github.com/SUSE/ha-sap-terraform-deployments/blob/develop/salt/monitoring/prometheus/prometheus.yml.j2#L31
> Set correct ip to monitor for hana in non HA scenario

- salt/cluster_node/ha/iscsi_initiator.sls
- salt/pillar/iscsi_srv.sls
Package `targetcli-fb-common` and `python3-targetcli-fb` not exist in SLE12SP4.
> Correct the iscsi target package in SLE12SPx.

- gcp/modules/hana_node/salt_provisioner.tf
- gcp/modules/netweaver_node/salt_provisioner.tf
- salt/hana_node/download_hana_inst.sls
- salt/hana_node/files/rclone/gcp.conf
- salt/macros/download_from_google_storage.sls
- salt/netweaver_node/installation_files.sls
Implementation to replace `rclone` by the official GCP tools (gcloud and gsutil). We cannot use non official 3 party tools like `rclone`, so using the GCP provided tools make sense.
The usage for the user will be exactly the same (it must provide the bucket path and the credentials file). 
I have created the implementation in a macro in order to avoid duplicated code, but if it's too confusing I can just copy/paste the states in HANA and NW.
PD: Even though it's not strictly needed, I have added 2 states to configure the `gcloud` usage so the user can use it later. It's a quite standard tool, so it makes sense. I can remove them anyway (I'm talking about `add_gcloud_path` and `restart_shell` states)
Some info about the official docs:
https://cloud.google.com/sdk/docs/downloads-interactive …
> Replace rclone by gcloud tools

- salt/netweaver_node/installation_files.sls
fixes the following error:
```
local:
Data failed to compile:
----------
Rendering SLS 'predeployment:netweaver_node.installation_files' failed: Jinja syntax error: unexpected ']', expected ')'; line 53
---
[...]
{% from 'macros/download_from_google_storage.sls' import download_from_google_storage with context %}
{{ download_from_google_storage(
grains['gcp_credentials_file'],
grains['netweaver_software_bucket']],    <======================
sapcd) }}
{% elif grains['provider'] == 'aws' %}
download_files_from_s3:
[...]
---
```
> Fix salt syntax error

- salt/cluster_node/monitoring.sls
I have branched everything in [network:ha-clustering:sap-deployments:devel](https://build.opensuse.org/project/show/network:ha-clustering:sap-deployments:devel) so we don't need `server:monitoring` anymore.
> remove server:monitoring repository configuration

- libvirt/main.tf
- libvirt/modules/drbd_node/salt_provisioner.tf
- libvirt/modules/drbd_node/variables.tf
- libvirt/modules/hana_node/salt_provisioner.tf
- libvirt/modules/hana_node/variables.tf
- libvirt/modules/iscsi_server/salt_provisioner.tf
- libvirt/modules/iscsi_server/variables.tf
- libvirt/modules/monitoring/salt_provisioner.tf
- libvirt/modules/monitoring/variables.tf
- libvirt/modules/netweaver_node/salt_provisioner.tf
- libvirt/modules/netweaver_node/variables.tf
- libvirt/variables.tf
I have create a new terraform module `common_variables` to store the variables that are shared among all of the modules, like the registration code, email, ha repo, etc
The idea of the implementation is to reduce the amount of variables we need to pass from the main terraform file to the modules, wrapping them all in a unique module. It reduces a lot the amount of duplicated code.
After this, it will be easier to add/remove new variables that are common to all the modules (like removing the `qa_mode` and adding new variables like `colored_output` or `offline_provisioning`.
Let me know what do you think? If you like the approach, I will expand the implementation to the other cloud providers, and eventually replace the `qa_mode` variable by other more meaningful options
> Create common_variables module

- pillar_examples/automatic/drbd/cluster.sls
- pillar_examples/automatic/hana/cluster.sls
- pillar_examples/automatic/netweaver/cluster.sls
PIllar examples in `automatic` folder fixed to get a default value for the `sbd_disk_device`. This was causing an error in the cloud providers after https://github.com/SUSE/ha-sap-terraform-deployments/pull/511
As before the pillar files `top.sls` files were splited in multiple files, this value was not needed in the 1st salt execution (which sets this value properly)
PD: Libvirt was not affected as `sbd_disk_device` always has a value
> Set default value to sbd_device_disk in pillar

- pillar_examples/automatic/hana/cluster.sls
Our jenkins CI tests are failing many times due the joining cluster operations timeout. This happens because the 1st node needs more time than the 2nd, depending how the HANA installation is done (and mostly the HA enablement actions).
Increasing this timeout should fix the issues (most of the times it fails for 30 seconds or so, let's put more time just in case hehe)
> Increase cluster join timeout

- salt/cluster_node/ha/iscsi_initiator.sls
After open-iscsi has been upgraded to 2.1.2 version, the initiatorname.iscsi file is not shipped by default,and it's created with iscsi-init service.
More information in: https://build.opensuse.org/package/view_file/network/open-iscsi/open-iscsi.changes?expand=1
The new version has only been shipped to SLE15SP2, that's why the filter is set.
**PD: This change should be backported to master branch at some point if we don't plan a new release soon, as it has the same impact there**
> Run iscsi-init service to create initiatorname.iscsi file

- salt/provision.sh
This PR:
1)  add `log_ok` and `log_error` helper function and adapt them in script. 
2) Print during execution only salt `error` and a resume of state at the end. 
3) create a `phase` logger a first v1 of logger, with colors which says the status of phase  with timestamp, hostname and msg
4) add back the colored output
We do have also a `debug` file for the full verbose mode in case needed .
> Improve logging and debugging in context of logs format

- aws/main.tf
- aws/variables.tf
- azure/main.tf
- azure/variables.tf
- doc/troubleshooting.md
- gcp/main.tf
- gcp/variables.tf
- generic_modules/common_variables/outputs.tf
- generic_modules/common_variables/variables.tf
- libvirt/main.tf
- libvirt/variables.tf
- salt/provision.sh
`provisioning_log_level` variable added to the deployment. Now, we can decide from a user perspective which log level we want to use in our deployments.
I have put `error` by default. The old output was `info`, and we log as `debug` in the log files.
PD: I have indented some lines in `provision.sh` too
> Add provisioning_log_level variable

- salt/cluster_node/ha/iscsi_initiator.sls
- salt/netweaver_node/nfs.sls
this PR fix `false` failure we print as error. Is better to use quiet so we don't print errors which aren't
> Make output quite for command who check only

- aws/README.md
- doc/qa.md
- doc/troubleshooting.md
- generic_modules/salt_provisioner/main.tf
- salt/provision.sh
Log properly the salt execution result summary to a file (besides the standard output)
Besides that, I have changed the `provisioning.log` file name to `salt-result.log`.
**PD: Now the `provision.sh` is executed with `bash` what makes sense as actually it was defined in the shebang. I don't really know why we put `sh` honestly...**
> Fix salt result output logging issues

- salt/cluster_node/ha/iscsi_initiator.sls
The re-provisioning of `predeployment` fails if we use `iscsi` as the `iscsiadm` command already finds an existing session.
This `unless` command will check this, and ignore the state if a session is on place
> Make iscsi initiator state idempotent

- generic_modules/common_variables/outputs.tf
Fix the SSH keys logic in Libvirt, as I removed the correct logic accidentally.
It looks like terraform's `fileexists` doesn't work properly with empty strings `""` raising an error:
```
on ../generic_modules/common_variables/outputs.tf line 2, in locals:
2:   public_key      = fileexists(var.public_key) ? file(var.public_key) : var.public_key
|----------------
| var.public_key is ""
Call to function "fileexists" failed: . is not a regular file, but
"drwxr-xr-x".
```
This commit fixes this and the subsequent error as the `authorized_keys` grains was populated with an empty string too:
```
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): [DEBUG   ] LazyLoaded ssh_auth.present
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): …
```
> Fix ssh keys usage in libvirt to avoid empty strings

- pillar_examples/automatic/drbd/cluster.sls
- pillar_examples/automatic/hana/cluster.sls
- pillar_examples/automatic/netweaver/cluster.sls
Time to time, the cluster joining process fails because the 1st node is not totally initialized (specially in Azure).
To avoid that, I have set a really conservative time that won't make a big difference in the overall deployment time, but it will avoid these errors.
> Increate wait_for_initialization to 120 to avoid sporadic errors

- salt/os_setup/registration.sls
Workaround for the `sap-blue-horizon` branch to install the monitoring server packages from PackageHub.
Until we have some better official solution to get the supported packages, PackageHub is the best option.
> Add PackageHub usage for the monitoring server

- salt/monitoring_srv/prometheus/rules.yml
Some of the alerts have outdated queries that did not take into accounts the changes we've been doing in `ha_cluster_exporter`.
> Fix Prometheus alerts

- azure/modules/bastion/main.tf
- azure/modules/bastion/outputs.tf
- azure/modules/bastion/salt_provisioner.tf
- salt/top.sls
The bastion provisioning was not done if the monitoring machine was not created. This creates issues as some other important states (update machine, authorize ssh keys, etc) are not executed.
Now, `os_setup` is always executed, and states in `bastion` will be only executed if `monitoring` is enabled as we only setup nginx there to proxy grafana dashboards to the bastion machine.
I took advantage and renamed the internal variable `bastion_enabled` to `bastion_count` as it is more meaningful
> Run bastion provision without monitoring

- salt/monitoring_srv/grafana.sls
The latest version of Grafana changes the configuration slightly so the salt state would not match it anymore. I made it more generic so that it shouldn't fail in the future.
> Fix Grafana configuration

- aws/main.tf
- aws/terraform.tfvars.example
- aws/variables.tf
- azure/main.tf
- azure/terraform.tfvars.example
- azure/variables.tf
- gcp/main.tf
- gcp/terraform.tfvars.example
- gcp/variables.tf
- generic_modules/common_variables/outputs.tf
- generic_modules/common_variables/variables.tf
- libvirt/main.tf
- libvirt/terraform.tfvars.example
- libvirt/variables.tf
- salt/provision.sh
Implementation of a non colored provisioning output. 
It adds the `provisioning_output_colored` variable to decide whether the provisioning scripts output is colored or not.
Until now, this was done using the `qa_mode` option.
This feature is a good go have thing if the project is used in environments such as blue-horizon.
To use ansii output colors in html is not trivial, as you need to translate all the characters by html tags and span entries, and besides that, salt/terraform combo doesn't just put colors in individual lines, so it makes things really difficult. I think going colorless is the best by now.
**INFO: Unfortunately the `SUSEConnect` tool doesn't have the option to disable colors, so this command output always be colored...*
> Add provisioning_output_colored variable

- azure/infrastructure.tf
- salt/hana_node/init.sls
- salt/hana_node/saptune_exporter.sls
- salt/monitoring_srv/grafana.sls
- salt/monitoring_srv/grafana/dashboards/tuning.json
- salt/monitoring_srv/prometheus/prometheus.yml.j2
review commit by commit so you have less files
This pull-request add:
- the new `tuning.json` dashboard which is the saptune_exporter dashboard
- an option for grafana.ini to allow dashboards/panels to be embedded (by default this is disabled by grafana)
- add the saptune_exporter systemd-service activation on hana nodes
> blue horizon tuning dashboard and exporter setup

- azure/outputs.tf
This value is consumed by blue-horizon to format the correct grafana iframe urls.
Here an example:
http://%{bastion_ip}:3000/d/EcC4JDFWz2/sap-hana?orgId=1&var-DS_PROMETHEUS=Prometheus&var-node_name=hana01&var-node_ip=%{hana_ip}&var-sid=%{sid}&var-instance_number=00&var-database_name=%{sid}&kiosk
**bastion_ip and sid can be already retrieved**
> Output hana virtual ip

- salt/bastion/nginx.sls
- salt/cluster_node/ha/network.sls
- salt/cluster_node/monitoring.sls
- salt/monitoring_srv/grafana.sls
- salt/monitoring_srv/loki.sls
Current code tries to enable the network service which lead to an error on SLE15-SP3 because service is already enabled.
In fact, it's not really needed to enable this service, so better to remove this `Enable:` option.
This PR also force-adds the `CLOUD_NETCONFIG_MANAGE` option, to ensure that there will be no issues if `cloud-init` is used.
Tested on 15-SP2 and 15-SP3 images.
> Fix network restart on SLE15-SP3

- salt/monitoring_srv/prometheus/prometheus.yml.j2
The saptune exporter is executed in all the HANA nodes (all of the HANA nodes must have the solution applied), so it must be targeted there, and not using the virtual ip address (which actually, should go in the Load balancer in this case to redirect the port, otherwise it wouldn't work).
The change just fixes the target to query the individual HANA nodes
> Target the correct hana machines with the saptune exporter

- salt/monitoring_srv/grafana/dashboards/tuning.json
Add new dashboard according expected layout
> Tuning dashboard new version

- azure/infrastructure.tf
Define a specific version for the `null` provider.
This is required to avoid the download of the latest version, and as we ship this provider under SLE, we must use the provided version.
> Define specific version for null provider

- salt/hana_node/mount/azure.sls
Fix how the LVM volumes are created in azure when multiple luns are involved.
This is needed for disk configuration such as:
```
hana_data_disks_configuration = {
disks_type       = "Premium_LRS,Premium_LRS,Premium_LRS,Premium_LRS,Premium_LRS,Premium_LRS"
disks_size       = "512,512,512,512,64,512"
caching          = "ReadOnly,ReadOnly,ReadOnly,ReadOnly,ReadOnly,None"
writeaccelerator = "false,false,false,false,false,false"
luns             = "0,1,2#3#4#5"
names            = "datalog#shared#usrsap#backup"
lv_sizes         = "70,100#100#100#100"
paths            = "/hana/data,/hana/log#/hana/shared#/usr/sap#/hana/backup"
}
```
Check how 2 LVMs are created for `datalog` (`/hana/data` which uses the 70% of disk size of luns `0,1,2` and `/hana/log` which uses the remaining empty space until …
> Fix how the lvm is created in azure with multiple luns

- salt/netweaver_node/installation_files.sls
This error was introduced form some incorrect merge.
Port commit already present in `develop` branch.
Fix for: https://github.com/SUSE/ha-sap-terraform-deployments/issues/617
> Fix issue in NW software download

- salt/os_setup/repos.sls
Set higher priority to the devel repo if it's used (90, 99 is the default value).
This aims for:
- Use all the packages from the devel repository if this is added
Drawback:
- Now, we cannot have the combination of: the project uses the packages from SLE if found and from the devel project otherwise (in this case the higher version would win). I would say that this functionality is not good, but this is how it was working (and being used by now). This requires having all the involved packages in SLE to use the `non devel repo` option (which potentailly threatens the option to have the monitoring solution in SLE12, with supported deployment packages)
> Set higher priority to the devel repo

- pillar_examples/automatic/hana/hana.sls
Fix for: https://github.com/SUSE/ha-sap-terraform-deployments/issues/626
The pillar file was incorrectly checking for the content. We introduced some change during the course of the development that is normalizing the `/etc/salt/grain` file content. This means, that the entries with empty value are changed to `null` value.
Initially the pillar was designed for:
```
hana_cluster_vip_secondary:
```
But now the file is changed to:
```
hana_cluster_vip_secondary: null
```
So, the if statement fails. With the new comparison the operation mode is properly set based in `hana_active_active` parameters.
Tested in libvirt and gcp.
> Fix hana_cluster_vip_secondary grain usage in pillar file

- pillar_examples/automatic/drbd/cluster.sls
- pillar_examples/automatic/hana/cluster.sls
- pillar_examples/automatic/netweaver/cluster.sls
Fix for: https://github.com/SUSE/ha-sap-terraform-deployments/issues/624
FYI: @ab-mohamed
Updated some values of corosync in GCP deployment. 
The new result is:
```
totem {
version: 2
secauth: off
crypto_hash: sha1
crypto_cipher: aes256
cluster_name: hana_cluster
clear_node_high_bit: yes
token: 20000
token_retransmits_before_loss_const: 10
join: 60
consensus: 24000
max_messages: 20
interface {
ringnumber: 0
mcastport: 5405
ttl: 1
}
transport: udpu
}
logging {
fileline: off
to_stderr: no
to_logfile: no
logfile: /var/log/cluster/corosync.log
to_syslog: yes
debug: off
timestamp: on
logger_subsys {
subsys: QUORUM
debug: off
}
}
nodelist {
node {
ring0_addr: 192.168.1.11
nodeid: 1
}
node {
ring0_addr: 192.168.1.12
nodeid: 2
}
}
quorum {
provider: corosync_votequorum
expected_votes: 2
two_node: …
```
> Set new configuration values for corosync for gcp

- salt/bastion/init.sls
- salt/top.sls
Currently if you don't have monitoring enabled the bastion role fails with:
```
local:
----------
ID: states
Function: no.None
Result: False
Comment: No Top file or master_tops data matches found. Please see master log for details.
Changes:   
Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
```
> install nginx only if monitoring enabled - move condition into bastion/init.sls

- salt/os_setup/registration.sls
Add PackageHub usage to the Hana nodes deployment. This is needed to get `prometheus-saptune_exporter` from official SUSE channels
> Add PackageHub usage to hana nodes to get saptune exporter

- pillar_examples/automatic/netweaver/netweaver.sls
Remove S4HANA specific extra parameters as they are set now in the `sapnwbootstrap-formul`. These parameters are mandatory and are now set in the formula always if S4HANA is installed.
Based on:
https://github.com/SUSE/sapnwbootstrap-formula/pull/80
> Remove S4HANA specific extra parameters

- gcp/modules/drbd_node/salt_provisioner.tf
- pillar_examples/automatic/drbd/drbd.sls
DRBD have to use different backing device in GCP to support multiple google disks attached.
Use "by-id: /dev/disk/by-id/google-*" as backing device.
In GCP, it is like /dev/disk/by-id/google--disk-drbd--part1
Need to align pillar file to use the template res_single_vol_v9.j2
Need to align with corresponding pull request of drbd-formula(0.4.1) SUSE/drbd-formula#19
> bsc#1179529 - Support use different backing device per node

- azure/modules/netweaver_node/main.tf
- gcp/modules/netweaver_node/salt_provisioner.tf
- libvirt/modules/netweaver_node/main.tf
I have found some errors running some deployments in non HA scenarios.
- In Azure and GCP some non created resources are referenced
- In Libvirt there was an incorrect usage of one variable for Netweaver
> Fix errors in non HA scenarios

- salt/provision.sh
There are two lines where x86_64 is hardcoded.  The hardcoded architecture is replaced with a command to determine the architecture at runtime.
> Fix hardcoded architecture

- salt/os_setup/packages.sls
Freeze the packages version involved in the deployment automation. This is needed to avoid errors if non backward compatible changes are introduced, specially in the formulas (which is quite common by now).
Some context:
As we don't expect to continue adding new features to this 1st version of the console project, having frozen packages is the best option. This will avoid unexpected errors in the future.
I have noticed that all the versions are stored in our SCC channels, so it gives the option to specify versions.
It is a pretty straightforward change and doesn't imply major consequences as we want to always stay in these versions.
The used versions are the current latest versions in the SLES4SAP product (all the testing has been done with them). When new versions are submitted, the same …
> Freeze deployment automation package versions

- salt/monitoring_srv/prometheus.sls
Start prometheus alertmanager properly.
Fix for: https://github.com/SUSE/ha-sap-terraform-deployments/issues/665
> Start prometheus alertmanager

- .ci/validate-terraform.sh
- .travis.yml
This installs terraform-provider-libvirt in travis and enables checks on libvirt provider again.
> install terraform-provider-libvirt in travis

- salt/hana_node/mount/gcp.sls
Fix for the salt state that creates the LVMs in GCP. Now the used size is the correct one.
Fix for https://github.com/SUSE/ha-sap-terraform-deployments/issues/683 
The issue happens due a lack of disk space on HANA to install S4/HANA
> Fx gcp disk lvm size

- aws/modules/drbd_node/salt_provisioner.tf
- doc/deployment-templates.md
- doc/drbd.md
- libvirt/variables.tf
... as well as `drbd_shared_storage_type`. I can't find it reused anywhere.
> docs(#491): removes references to `shared_storage_type`

- gcp/infrastructure.tf
- gcp/main.tf
- gcp/modules/bastion/main.tf
- gcp/modules/iscsi_server/main.tf
- gcp/modules/monitoring/main.tf
- gcp/terraform.tfvars.example
- gcp/variables.tf
If you PAYG images are used, the deployment fails due the lack of connection ports to get the packages from SCC. This is due the low number of `minimum ports per VM` of the NAT resource. Increasing this value fixes the issue.
Now the value is configurable.
Fix for:https://github.com/SUSE/ha-sap-terraform-deployments/issues/693
FYI: @ab-mohamed
**Edit**: The 2nd commit (https://github.com/SUSE/ha-sap-terraform-deployments/pull/694/commits/c9e8a124c4c9dcc443a0be6ca0e6a9a0a0e21c44) fixes the Monitoring and iSCSI machines deployment when the bastion host is used and the other machines are using PAYG images
> GCP - Increase the NAT mininum nuamber of ports for the bastion - Monitoring PAYG fixed

- pillar_examples/automatic/hana/cluster.sls
- pillar_examples/automatic/netweaver/cluster.sls
- pillar_examples/libvirt/cost_optimized/cluster.sls
- pillar_examples/libvirt/performance_optimized/cluster.sls
This sets `unicast: True` in the libvirt pillars.
This is the same value as in any other cloud provider.
> "unicast: True" in libvirt pillars

- aws/main.tf
- azure/main.tf
- azure/variables.tf
- gcp/main.tf
- libvirt/main.tf
- openstack/main.tf
This fixes:
- a logic error in defining `monitoring_netweaver_targets_ha` #724.
- set default values for azure native fencing variables
> fix monitoring and azure native fence default values

- generic_modules/salt_provisioner/main.tf
Missed adding this change to PR [powervs: Enable bastion private network #727](https://github.com/SUSE/ha-sap-terraform-deployments/pull/727)
> powervs: Add bastion host info to connection details

- powervs/modules/hana_node/salt_provisioner.tf
- powervs/terraform.tfvars.example
- powervs/variables.tf
- salt/hana_node/download_hana_inst.sls
- salt/hana_node/hana_inst_media.sls
- salt/hana_node/init.sls
Installing SAP HANA from an NFS server was used for testing prior to this pull request.  This pull request uses the more cost effective method which downloads SAP media from IBM Cloud Object Storage.
> Switch to using IBM Cloud Object Storage

- azure/modules/hana_node/main.tf
This fixes #742 by adding port 5XX13 to the azure load balancer.
> fix for azure S/4HANA 1909 DB import fails

- aws/modules/netweaver_node/main.tf
- azure/modules/netweaver_node/main.tf
- gcp/modules/netweaver_node/main.tf
The Netweaver virtual IPs for AS/ERS are reachable via different mechanism for public clouds:
- azure -> load-balancer
- gcp -> route to VM (changed by cluster)
- aws -> route to VM (changed by cluster)
For the Netweaver virtual IPs for PAS/AAS there is currently no mechanism implemented to make them reachable to other nodes.
Therefore the current monitoring setup #740 is also broken.
This PR makes these PAS/AAS virtual IPs reachable via these mechanisms:
- azure -> vIP on network interface on VMs
- load-balancer setup would also be possible in theory but is way more complex (e.g. create rules per node)
- gcp -> route to VM (static)
- aws -> route to VM (static)
In addition to that there are fixes included to not only deploy AS routes in HA scenarios.
```
count = local.create_ha_infra
vs. …
```
> make Netweaver PAS/AAS virtual IPs reachable on public cloud setups

- salt/os_setup/minion_configuration.sls
This fixes an issue which comes with the updated rpm `salt-standalone-formulas-configuration-3002.2-46.1` which introduces a new file `/etc/salt/minion.d/standalone-formulas-configuration.conf` that overwrites our `base/predeployment` environments in `/etc/salt/minion`.
This should be a permanent fix as long as there is no tampering with the environments by additional rpms.
All other minion settings are now in separate config files, too.
> develop: add minion.d files for each environment (base/predeployment)

- Makefile
- doc/fencing.md
This fixes the failing "Ci tests / markup link checker" tests.
> ci: ignore www.linux-ha.org links as site is down since days

- generic_modules/common_variables/outputs.tf
Variable `pkg_requirements` can be uninitialized if `requirements.yml` file is delete. As this file is optional, the variable needs to be initialized with an empty value.
> develop: Fix 'pkg_requirements' empty variable

- generic_modules/common_variables/outputs.tf
Variable `pkg_requirements` can be uninitialized if `requirements.yml` file is delete. As this file is optional, the variable needs to be initialized with an empty value.
> master: Fix 'pkg_requirements' empty variable

- azure/variables.tf
SBD on ISCSI shouldn't need that big of a vm.
> Change azure default iscsi vm size

- salt/os_setup/packages.sls
In #731 the `kernel-default-base` removal code was changed to only run on the iscsi target server.
This PR reverts to the old behavior it and adds a more reliable way to switch kernels.
Without the new way of switching kernels, I get the following error messages:
```
module.bastion.module.bastion_provision.null_resource.provision[0] (remote-exec): ----------
module.bastion.module.bastion_provision.null_resource.provision[0] (remote-exec):           ID: kernel-default-base
module.bastion.module.bastion_provision.null_resource.provision[0] (remote-exec):     Function: pkg.removed
module.bastion.module.bastion_provision.null_resource.provision[0] (remote-exec):       Result: True
module.bastion.module.bastion_provision.null_resource.provision[0] (remote-exec):      Comment: All targeted …
```
> Kernel default base remove

- requirements.yml
- salt/drbd_node/custom_handlers.sls
- salt/hana_node/init.sls
- salt/majority_maker_node/init.sls
Bug fixes for hana_node/drbd_node:
1. Fix wait_until_ssh_is_ready_xxx failure after timeout when no cluster_ssh_pub/cluster_ssh_key defined
Salt state 'wait_until_ssh_is_ready_xxx' in 'wait.sls' is introduced in scale out feature.
It depends on the ssh keys (cluster_ssh_pub/cluster_ssh_key) of clusters and only deployed via 'cluster_node/ha/ssh.sls' (cluster_node/ha/init.sls)
Without the two keys defined in tfvars file, 'wait.sls' will wait until
failure. And wait.sls is not a must in non scale out hana scenario.
Only run the state when ssh key available.
2. drbd_node: allow create parent directory of notify-split-brain-haclusterexporter-suse-metric.sh
3. fix the requirements.yml for saphanabootstrap-formula since the template name is changed.
> Fix wait_until_ssh_is_ready_xxx failure in libvirt and correct requirements for hana_node

- aws/modules/netweaver_node/main.tf
- azure/modules/netweaver_node/main.tf
- gcp/modules/netweaver_node/main.tf
This fixes #781 and is a direct port of #750.
The Netweaver virtual IPs for AS/ERS are reachable via different mechanism for public clouds:
- azure -> load-balancer
- gcp -> route to VM (changed by cluster)
- aws -> route to VM (changed by cluster)
For the Netweaver virtual IPs for PAS/AAS there is currently no mechanism implemented to make them reachable to other nodes.
Therefore the current monitoring setup #740 is also broken.
This PR makes these PAS/AAS virtual IPs reachable via these mechanisms:
- azure -> vIP on network interface on VMs
- load-balancer setup would also be possible in theory but is way more complex (e.g. create rules per node)
- gcp -> route to VM (static)
- aws -> route to VM (static)
In addition to that there are fixes included to not only deploy AS routes in HA …
> master: make Netweaver PAS/AAS virtual IPs reachable on public cloud setups

- salt/hana_node/wait.sls
- salt/majority_maker_node/init.sls
- salt/majority_maker_node/wait.sls
- ssh commands will not hang anymore because of password promt
- make sure `saphanabootstrap-formula` is installed in majority maker
> hana scale-out: fix ssh test and make it more resilient

- aws/modules/netweaver_node/main.tf
- gcp/modules/netweaver_node/main.tf
The deployment in AWS is failing if Netweaver is not enabled:
```
Error: Invalid index
on modules/netweaver_node/main.tf line 46, in resource "aws_route" "nw-pas-route":
46:   instance_id            = aws_instance.netweaver.0.id
|----------------
| aws_instance.netweaver is empty tuple
The given key does not identify an element in this collection value.
```
This fix basically checks if there is any NW vm before checking the current condition and create the route
> Disable nw-pas-route creation if nw is not enabled

- openstack/modules/netweaver_node/main.tf
This will allow all virtual IPs to be bindable/reachable on on the netweaver cluster.
> openstack: fix netweaver virtual IPs on ports

- salt/nfs_srv/directories.sls
- salt/nfs_srv/init.sls
- salt/nfs_srv/lvm.sls
- salt/nfs_srv/nfs.sls
- salt/nfs_srv/packages.sls
- salt/top.sls
This is a prerequisite to deploy HANA scale-out on libvirt/openstack. It should not be used for production workloads.
> add minimal NFS server to be used on libvirt/openstack (instead of DRBD) - not for production workloads

- aws/main.tf
- azure/main.tf
- libvirt/main.tf
- openstack/main.tf
These formula changes make it mandatory to set a valid `*_vip_mechanism` for each cluster setup.
* https://github.com/SUSE/saphanabootstrap-formula/pull/137
* https://github.com/SUSE/sapnwbootstrap-formula/pull/91
* https://github.com/SUSE/drbd-formula/pull/28
Currently we mostly set `""` which will result in the grains beeing `null` which is not interpretable by the formulas.
> set default VIP mechanisms to support latest DRBD, HANA, Netweaver formulas

- .github/workflows/ci.yml
- .salt-lint
- salt/hana_node/mount/init.sls
Somehow `salt-lint` is not executed in the CI.
> ci: enable salt-lint again (was missing)

- .github/workflows/ci.yml
- .salt-lint
Somehow `salt-lint` is not executed in the CI.
> master ci: enable salt-lint again (was missing)

- salt/cluster_node/monitoring.sls
The rpm `loki-2.4.1+git.1636374074.f61a4d261` updated in https://build.opensuse.org/request/show/940653 removed the `loki` user and now runs as root.
We need to adapt this in our promtail setup.
> remove loki user from promtail setup

- generic_modules/common_variables/outputs.tf
- pillar_examples/automatic/netweaver/netweaver.sls
This completes the feature of creating a HANA DB backup after the initial "Netweaver / S/4HANA import" is done (if HANA SR is enabled) in https://github.com/SUSE/sapnwbootstrap-formula/pull/95.
It introduces a new pillar switch called `netweaver.hana.ha_enabled` for this.
After the very large initial "Netweaver / S/4HANA import", the 1st backup on the HANA (done by `saphanabootstrap-formula`) differs to much to re-initiate HANA System Replication. This is why this new backup is needed.
Tested and verified on Azure and GCP with S/4HANA 2021.
https://github.com/SUSE/ha-sap-terraform-deployments/issues/739
https://github.com/SUSE/ha-sap-terraform-deployments/issues/803
https://github.com/SUSE/sapnwbootstrap-formula/pull/95
`salt-shaptools-0.3.14` including these fixes: …
> add grain/pillar to let netweaver know about HANA HA/SR

- generic_modules/on_destroy/on_destroy.sh
- salt/os_setup/registration.sls
From https://www.suse.com/c/byos-instances-and-the-suse-public-cloud-update-infrastructure/:
>For BYOS images with a datestamp later than 20220103, spare -chost- images, the cloud-regionsrv-client package will be installed by default to make registration more straight forward. Unlike for on-demand instances the registration is not automatic on instance startup. The reason for this is that your SUSE registration code is required for access to the update infrastructure.
This means, that never public cloud images in azure/aws/gcp should use `registercloudguest` to connect to the update servers.
This PR introduces:
- use `registercloudguest` if it available (baked into the image)
- update old workaround that is broken with new `registercloudguest` releases
- fixes #812 
```
os_image = …
```
> use `registercloudguest` where available and rework PAYG workaround

- generic_modules/on_destroy/on_destroy.sh
- salt/os_setup/registration.sls
From https://www.suse.com/c/byos-instances-and-the-suse-public-cloud-update-infrastructure/:
>For BYOS images with a datestamp later than 20220103, spare -chost- images, the cloud-regionsrv-client package will be installed by default to make registration more straight forward. Unlike for on-demand instances the registration is not automatic on instance startup. The reason for this is that your SUSE registration code is required for access to the update infrastructure.
This means, that never public cloud images in azure/aws/gcp should use `registercloudguest` to connect to the update servers.
This PR introduces:
- use `registercloudguest` if it available (baked into the image)
- update old workaround that is broken with new `registercloudguest` releases
- fixes #812 
```
os_image = …
```
> master: use `registercloudguest` where available and rework PAYG workaround

- gcp/infrastructure.tf
- gcp/main.tf
> gcp: only use 2 compute zones to have an even distribution of nodes

- aws/infrastructure.tf
- aws/main.tf
- aws/modules/netweaver_node/main.tf
- aws/modules/netweaver_node/salt_provisioner.tf
- aws/modules/netweaver_node/variables.tf
- aws/terraform.tfvars.example
- aws/variables.tf
- generic_modules/common_variables/netweaver_variables.tf
- pillar_examples/automatic/netweaver/cluster.sls
- pillar_examples/automatic/netweaver/netweaver.sls
- salt/netweaver_node/nfs.sls
- salt/shared_storage/nfs.sls
https://github.com/SUSE/ha-sap-terraform-deployments/pull/733 and https://github.com/SUSE/ha-sap-terraform-deployments/pull/796 introduced new mechanisms to handle shared storage for Netweaver and HANA scenarios.
These are now adapted for AWS netweaver deployments in this PR.
It includes:
- deploy EFS resources inside Netweaver module
- EFS is still default (DRBD is an alternative)
- use same code as for azure/openstack `salt/shared_storage/nfs.sls`
This also fixes #832
> aws: adapt netweaver EFS shared storage to mechanisms from other cloud providers

- salt/cluster_node/init.sls
The SLES 15 SP4 QA is failing at the moment because the `cloud_provider` grains is not set.
```
2022-05-24 07:54:37,589 [salt.state       :318 ][ERROR   ][8024] Unable to manage file: Jinja variable 'dict object' has no attribute 'cloud_provider'
```
It does not always fail and not on every cloud provider (only azure so far), so I suspect a race condition as mentioned in here https://github.com/saltstack/salt/issues/54331 with salt >= 3003.
To workaround this condition, we can simply make sure that the `cloud_provider` grain is already set in the `salt-deployment` run.
> make sure cloud_provider grain is set on SLES 15 SP4 (salt-3004)

- salt/cluster_node/ha/sbd.sls
If the iSCSI server AND any cluster node reboots, the device name of the SBD device attached via iSCSI e.g. `'/dev/disk/by-id/scsi-${WWN}` will change.
The new approach uses `/dev/disk/by-path/ip-${ISCSI_SRV_IP}:3260-iscsi-${IQN}-lun-0` which really is perstent accross reboots.
Tested and verified in libvirt and azure.
This solves #718.
> sbd: use iSCSI server IP and IQN instead of wwn to be reboot persistent

- gcp/main.tf
- gcp/modules/hana_node/main.tf
- gcp/modules/netweaver_node/main.tf
- gcp/modules/netweaver_node/salt_provisioner.tf
- gcp/terraform.tfvars.example
- gcp/variables.tf
- pillar_examples/automatic/netweaver/cluster.sls
- pillar_examples/automatic/netweaver/netweaver.sls
- salt/netweaver_node/nfs.sls
- salt/shared_storage/nfs.sls
https://github.com/SUSE/ha-sap-terraform-deployments/pull/733 and https://github.com/SUSE/ha-sap-terraform-deployments/pull/796 and https://github.com/SUSE/ha-sap-terraform-deployments/pull/834 introduced new mechanisms to handle shared storage for Netweaver and HANA scenarios.
These are now adapted for GCP netweaver deployments in this PR.
It includes:
- deploy filestore shared storage resources inside Netweaver module (similar to HANA scale-out implementation)
- DRBD is still default (filestore is an alternative)
- use same code as for aws/azure/openstack `salt/shared_storage/nfs.sls`
>  gcp: add filestore shared storage to netweaver

- salt/macros/download_from_google_storage.sls
Fix installation of `gcloud`tools on SLES12 by also passing `CLOUDSDK_PYTHON` to install script.
> gcp: fix install of gcloud tool on SLES12

- aws/README.md
- aws/terraform.tfvars.example
- azure/terraform.tfvars.example
- doc/sap_passwords.md
- gcp/terraform.tfvars.example
- generic_modules/common_variables/hana_variables.tf
- generic_modules/common_variables/netweaver_variables.tf
- libvirt/terraform.tfvars.example
- openstack/terraform.tfvars.example
As per suggestion https://github.com/SUSE/ha-sap-terraform-deployments/pull/873#issuecomment-1188279358, we now set this to 10-14 for HANA and Netweaver / S/4HANA deployments.
> common variables: set password length to 10-14 everywhere

- aws/README.md
- aws/infrastructure.tf
- aws/main.tf
- aws/modules/bastion/main.tf
- aws/modules/bastion/outputs.tf
- aws/modules/bastion/salt_provisioner.tf
- aws/modules/bastion/variables.tf
- aws/modules/drbd_node/main.tf
- aws/modules/drbd_node/salt_provisioner.tf
- aws/modules/drbd_node/variables.tf
- aws/modules/hana_node/main.tf
- aws/modules/hana_node/salt_provisioner.tf
- aws/modules/hana_node/variables.tf
- aws/modules/iscsi_server/main.tf
- aws/modules/iscsi_server/salt_provisioner.tf
- aws/modules/majority_maker_node/main.tf
- aws/modules/majority_maker_node/salt_provisioner.tf
- aws/modules/majority_maker_node/variables.tf
- aws/modules/monitoring/main.tf
- aws/modules/monitoring/salt_provisioner.tf
- aws/modules/monitoring/variables.tf
- aws/modules/netweaver_node/main.tf
- aws/modules/netweaver_node/salt_provisioner.tf
- aws/modules/netweaver_node/variables.tf
- aws/outputs.tf
- aws/terraform.tfvars.example
- aws/variables.tf
- azure/README.md
- gcp/README.md
- openstack/README.md
Needs #893 
This adds the option to deploy on AWS with a bastion host setup (enabled by default).
Only the bastion host will get a public IP. All other machines will be deployed in private subnets and will not be internet facing. They will have internet access through a NAT gateway though.
> aws: add option to deploy bastion host setup and private subnets
